#!/usr/bin/env python3
"""Central memory loader with L3 -> L2 -> L1 fallback hierarchy.

This module provides a single entry point for loading project memory
across the system (bootstrap, review bridge, pre-compact hook).

Memory hierarchy (loaded in order):
  L3 (memory_profile.md) — Brief, high-level project profile for quick context.
  L2 (memory_rules.md)   — Deterministic rules extracted by domain, parseable.
  L1 (observations.jsonl)— Raw observation records, limited to last N entries.

Usage:
    from bus.memory_loader import (
        get_bootstrap_context,
        get_review_context,
        get_compact_context,
        recall_observations,
    )

    ctx = get_bootstrap_context()  # L3 -> L2 -> L1 fallback
    review_ctx = get_review_context(domain="delivery-hygiene")
    compact_ctx = get_compact_context()
    obs = recall_observations(limit=10)

Design:
    - Fallthrough: each tier tries to load from its file; on failure or empty,
      it falls through to the next tier.
    - Deterministic: L2 and L3 files are regenerated by memory_consolidate.py
      and are deterministic given the same observations.jsonl.
    - Safe: never raises on missing/corrupted files; returns empty strings.
"""

import importlib
import json
import re
import sys
import types
from pathlib import Path
from typing import Any


_PROJECT_ROOT_BOOTSTRAP = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT_BOOTSTRAP) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT_BOOTSTRAP))

_RUNTIME_PACKAGE_ROOT = str(_PROJECT_ROOT_BOOTSTRAP / "runtime")
_runtime_pkg = sys.modules.get("runtime")
if _runtime_pkg is None:
    _runtime_pkg = types.ModuleType("runtime")
    _runtime_pkg.__path__ = [_RUNTIME_PACKAGE_ROOT]
    sys.modules["runtime"] = _runtime_pkg
else:
    runtime_paths = list(getattr(_runtime_pkg, "__path__", []))
    if _RUNTIME_PACKAGE_ROOT not in runtime_paths:
        runtime_paths.insert(0, _RUNTIME_PACKAGE_ROOT)
        _runtime_pkg.__path__ = runtime_paths

get_agent_dir = importlib.import_module("runtime.project_root").get_agent_dir

# WOT-2026-024r (A1): the portable archive reader. Imported from `bus/`, never
# from `scripts/reconcile_portable_memory.py` -- that would invert the dependency
# (bus -> scripts) and drag in `--apply` and the "promoted == is in a commit"
# semantics, which belong to reconcile and not to a reader.
from bus.portable_memory_archive import (  # noqa: E402
    CorruptArchiveError,
    dedup_key,
    is_lesson,
    read_archive_observations,
)


# Default max observations when falling back to raw L1.
_L1_FALLBACK_LIMIT = 15

# WOT-2026-024r (A2): cap on archive entries handed to `get_compact_context`.
# `pre_compact_hook.py` injects that string WHOLE and UNTRUNCATED, so an
# uncapped archive would land 30x the previous payload at the exact moment the
# session compacts for lack of context.
#
# SWEEP (snapshot 2026-08-03, archive of 175 entries; the numbers are EVIDENCE,
# the invariant is "bounded", not any particular figure):
#     cap  10 ->  3046 chars (~760 tokens)
#     cap  25 ->  7375 chars (~1840 tokens)
#     cap  50 -> 14831 chars (~3700 tokens)
#     cap 100 -> 29490 chars (~7370 tokens)
#     cap 175 -> 49526 chars (~12380 tokens)  <- uncapped today
# The cost is LINEAR (~74 chars/entry): there is no plateau and therefore no
# optimum to discover. Picking a cap is choosing a token budget, not tuning a
# threshold -- which is why this is a knob and not a contract. 50 buys ~3700
# tokens, roughly a third of today's archive and the NEWEST third, which is
# what a compaction needs. Below the cap nothing is dropped.
_COMPACT_ARCHIVE_CAP = 50


# --- Paths (computed lazily for testability) ---


def _get_memory_dir() -> Path:
    """Get the memory directory path.

    Before: Requires get_agent_dir() to be available.
    During: Computes path lazily each call (no caching) so tests can patch.
    After: Returns Path to .agent/runtime/memory/.
    """
    return get_agent_dir() / "runtime" / "memory"


def _get_observations_file() -> Path:
    """Get path to observations.jsonl."""
    return _get_memory_dir() / "observations.jsonl"


def _get_rules_file() -> Path:
    """Get path to memory_rules.md (L2)."""
    return _get_memory_dir() / "memory_rules.md"


def _get_profile_file() -> Path:
    """Get path to memory_profile.md (L3)."""
    return _get_memory_dir() / "memory_profile.md"


# --- Internal helpers ---


def _try_read_file(path: Path) -> str:
    """Read a text file safely, returning empty string on any error.

    Before: path must be a Path object.
    During: Reads the file with UTF-8 encoding, catching IOErrors.
    After: Returns file content as string, or '' if file missing/unreadable.
    """
    try:
        if path.exists():
            return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        pass
    return ""


def _read_observations(limit: int = _L1_FALLBACK_LIMIT) -> list[dict[str, Any]]:
    """Read the last N observations from observations.jsonl.

    Before: Requires observations.jsonl to exist (or returns empty list).
    During: Parses JSONL lines, keeping only valid dict entries.
            Reads from the end of the file to get the most recent entries.
    After: Returns a list of up to ``limit`` observation dicts, newest first.
           ``limit <= 0`` means unlimited (the whole file).
    """
    obs_file = _get_observations_file()
    if not obs_file.exists():
        return []

    try:
        text = obs_file.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []

    lines = text.splitlines()
    # Read from end to collect the most recent entries
    observations: list[dict[str, Any]] = []
    for line in reversed(lines):
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
            if isinstance(entry, dict):
                observations.append(entry)
                # limit <= 0 means unlimited (read the whole file)
                if limit > 0 and len(observations) >= limit:
                    break
        except json.JSONDecodeError:
            continue

    return observations


def _format_observations_as_text(observations: list[dict[str, Any]]) -> str:
    """Format a list of observation dicts as a markdown bullet list.

    Before: Requires a list of observation dicts (may be empty).
    During: Formats each entry as a bullet with timestamp, topic, signal, source.
    After: Returns a markdown string, or empty string if list is empty.
    """
    if not observations:
        return ""

    lines = [
        "# Raw Observations (L1 fallback)",
        "",
        f"Most recent {len(observations)} observations:",
        "",
    ]
    for obs in observations:
        ts = str(obs.get("timestamp") or "")[:19]
        topic = obs.get("topic", "general")
        signal = str(obs.get("signal") or "")[:200]
        source = obs.get("source", "unknown")
        lines.append(f"- [{ts}] **{topic}**: {signal} ({source})")

    return "\n".join(lines)


def _get_repo_root() -> Path:
    """Repo root that owns the portable archive.

    Derived from ``_get_memory_dir()`` (``<root>/.agent/runtime/memory``) rather
    than from ``get_agent_dir()`` so that any caller which redirects the memory
    dir -- as the existing tests do -- also redirects the archive. Resolving the
    root independently would let a test that patched only the memory dir still
    read the REAL motor archive: an isolation leak that turns a hermetic test
    into one that silently depends on this machine's memory.
    """
    return _get_memory_dir().parent.parent.parent


def _read_portable_archive() -> list[dict[str, Any]]:
    """Portable archive entries, or ``[]`` on any failure.

    WOT-2026-024r (A1): the tracked archive is the only memory surface that
    travels by git. Reading it is what turns it from write-only into memory.

    Fail-safe by contract of this module ("never raises"): a corrupt archive
    degrades the context instead of breaking every caller of the loader
    (bootstrap, review bridge, pre-compact hook). The fail-CLOSED barrier for a
    corrupt archive is ``validate_observations --strict``, wired in prepush.
    """
    try:
        return read_archive_observations(_get_repo_root())
    except (CorruptArchiveError, OSError, ValueError):
        return []


def _cap_by_recency(
    observations: list[dict[str, Any]], cap: int
) -> list[dict[str, Any]]:
    """The ``cap`` newest entries, or all of them when under the cap.

    WOT-2026-024r (A2). Bounds what `get_compact_context` hands to the
    pre-compact hook, which injects it untruncated. Sorting is explicit rather
    than assumed: the archive arrives in file-and-line order (oldest first), so
    slicing without sorting would keep the OLDEST entries -- the exact opposite
    of what a compaction needs.

    Before: ``observations`` may be in any order; ``cap`` is a positive int.
    During: sorts by ``timestamp`` descending; a missing timestamp sorts last
        (empty string) and never jumps ahead of a dated entry.
    After: returns at most ``cap`` entries, newest first. Never raises.
    """
    if len(observations) <= cap:
        return observations
    return sorted(
        observations,
        key=lambda obs: str(obs.get("timestamp") or ""),
        reverse=True,
    )[:cap]


def _format_archive_as_text(observations: list[dict[str, Any]]) -> str:
    """Format archive entries as a markdown section."""
    if not observations:
        return ""
    lines = [
        "# Portable Memory (tracked archive)",
        "",
        f"{len(observations)} lesson(s) that travel with the repo:",
        "",
    ]
    for obs in observations:
        ts = str(obs.get("timestamp") or "")[:19]
        topic = obs.get("topic", "general")
        signal = str(obs.get("signal") or "")[:200]
        ticket = obs.get("source_ticket") or obs.get("id") or "unknown"
        lines.append(f"- [{ts}] **{topic}**: {signal} ({ticket})")
    return "\n".join(lines)


# --- Public API ---


def get_bootstrap_context() -> str:
    """Load context for bootstrap: portable archive + best local tier.

    This is the primary entry point for session_bootstrap.md and any agent
    that needs a quick context summary of project memory.

    WOT-2026-024r (A1): the tracked portable archive is now ALWAYS included,
    not used as a last-resort fallback. Before this, memory promoted to the
    archive was versioned, pushed -- and read by nobody: the loader only ever
    looked at L3/L2/L1, all three gitignored. A backend cloning the repo got
    the archive and no way to reach it. Measured cost (2026-07-27): a lesson
    stored twice was repeated anyway and destroyed 7 tests. It was not a memory
    gap; it was memory written, versioned and never read.

    Before: memory files may or may not exist in the memory directory.
    During: reads the tracked archive, then the best available local tier
            (L3 profile -> L2 rules -> L1 raw observations). Entries the local
            tier already holds win over the archived copy: L1 is the LIVE copy
            and may have been edited after being archived, so on a stable-``id``
            collision the live entry is the newer truth.
    After: returns a markdown string combining both. Never returns None;
           returns empty string when there is no memory at all.
    """
    archived = _read_portable_archive()

    # Priority 1: L3 profile (brief, high-level)
    local = _try_read_file(_get_profile_file())
    if not local:
        # Priority 2: L2 rules (domain-organized rules)
        local = _try_read_file(_get_rules_file())
    live: list[dict[str, Any]] = []
    if not local:
        # Priority 3: L1 raw observations (last N entries)
        live = _read_observations()
        local = _format_observations_as_text(live)

    if archived and live:
        # Precedence is per ENTRY, not per source: drop the archived copy only
        # for entries the live tier already carries.
        seen = {dedup_key(entry) for entry in live}
        archived = [e for e in archived if dedup_key(e) not in seen]

    archive_text = _format_archive_as_text(archived)
    sections = [s for s in (archive_text, local) if s]
    return "\n\n".join(sections)


def _archive_for_domain(domain: str | None) -> list[dict[str, Any]]:
    """Archive entries relevant to ``domain`` (all of them when domain is None).

    WOT-2026-024r (A2). The archive entries carry a populated ``domain`` field
    that speaks the SAME vocabulary as this gate's callers -- measured on the
    real repo (2026-08-03): 175 entries, ZERO without a domain, across 9 values
    (`delivery-hygiene` 55, `review-quality` 55, `testing` 15, ...), and
    `delivery-hygiene` is literally the domain in this module's own usage
    example. So the filter keys on ``domain``, not on ``topic``/``source``:
    those are free-form labels, while ``domain`` is the field the review gate
    already reasons in.

    Why this matters more than it looks: L2 (`memory_rules.md`) only declares
    the domains `architecture` and `lesson`, so a review asking for
    `delivery-hygiene` matched NOTHING in L2 while 55 lessons on exactly that
    subject sat unread in the tracked archive.

    Before: no state required; the archive may be missing or corrupt.
    During: reads the archive (never raises) and keeps entries whose ``domain``
        matches case-insensitively.
    After: returns the matching entries, or ``[]``. A domain with no matches
        returns ``[]`` -- the caller decides what to do with that, and here it
        deliberately does NOT widen to the whole archive: dumping 175 unrelated
        lessons into a specialised review is the noise this filter exists to
        prevent.
    """
    archived = _read_portable_archive()
    if domain is None:
        return archived
    wanted = domain.strip().lower()
    return [e for e in archived if str(e.get("domain") or "").lower() == wanted]


def get_review_context(domain: str | None = None) -> str:
    """Load context for review: portable archive + L2 rules, falling back to L1.

    WOT-2026-024r (A2): the tracked archive is now read here too. Until this
    ticket only `get_bootstrap_context` (A1) and the recall gate (WOT-2026-047d)
    reached it, so the MANAGER's review context -- the one that decides whether
    work is approved -- was blind to every lesson that travels by git. See
    `_archive_for_domain` for the measured numbers and why the filter keys on
    ``domain``.

    Before: Requires optional domain string (e.g., 'delivery-hygiene').
    During: Reads archive entries for the domain, then L2 rules (filtered by
            domain when given). Falls back to L1 raw observations if L2 is
            empty. Precedence is per ENTRY only against L1, exactly as A1 does
            it: L2 is prose, not entries, so there is nothing to dedup against.
    After: Returns a markdown string combining the portable memory section and
           the local rules/observations. Never returns None.
    """
    archived = _archive_for_domain(domain)

    rules = _try_read_file(_get_rules_file())
    if not rules:
        observations = _read_observations()
        local = _format_observations_as_text(observations) if observations else ""
        if archived and observations:
            # Per-ENTRY precedence: the LIVE L1 copy wins, because it may have
            # been edited after being archived (same rule as A1).
            seen = {dedup_key(entry) for entry in observations}
            archived = [e for e in archived if dedup_key(e) not in seen]
    elif domain is None:
        local = rules
    else:
        # Filter rules by domain; no matching domain rules -> all rules.
        local = _filter_rules_by_domain(rules, domain) or rules

    archive_text = _format_archive_as_text(archived)
    sections = [s for s in (archive_text, local) if s]
    return "\n\n".join(sections)


def _has_wing_headers(rules_text: str) -> bool:
    """Check if the rules text uses the new Wing format (H2 Wing headers).

    Before: Requires the full text of memory_rules.md.
    During: Scans for ``## Wing:`` pattern.
    After: Returns True if Wing format detected, False otherwise.
    """
    return bool(re.search(r"^## Wing:\s+", rules_text, re.MULTILINE | re.IGNORECASE))


def _filter_rules_by_domain(rules_text: str, domain: str) -> str:
    """Filter memory_rules.md content to only include sections for a given domain.

    Before: Requires the full text of memory_rules.md and a domain string.
    During: Detects format (legacy H2 vs Wing H2/H3). Uses regex to find the
            matching ``## Domain: <domain>`` (legacy) or ``### Domain: <domain>``
            (Wing format) section and extract its content until the next Domain
            header or end of file.
    After: Returns the filtered section text, or empty string if domain not found.
            Retrocompat: if no Wing headers present, assumes legacy H2 format.
    """
    domain_lower = domain.lower()
    lines = rules_text.splitlines()

    # Detect format: Wing uses H3 (###), legacy uses H2 (##)
    has_wing = _has_wing_headers(rules_text)
    domain_pattern = r"^### Domain:\s*(.+)$" if has_wing else r"^## Domain:\s*(.+)$"
    domain_re = re.compile(domain_pattern, re.IGNORECASE)

    result_lines: list[str] = []
    in_target = False

    for line in lines:
        domain_match = domain_re.match(line)
        if domain_match:
            if in_target:
                break
            current_domain = domain_match.group(1).strip().lower()
            in_target = current_domain == domain_lower

        if in_target:
            result_lines.append(line)

    return "\n".join(result_lines).strip()


def get_compact_context() -> str:
    """Load combined context for pre-compact: portable archive + L3 + L2.

    WOT-2026-024r (A2): the tracked archive is now read here too. This gate
    feeds the pre-compact hook -- the moment a session is about to LOSE its
    context -- so it was the worst possible place to stay blind to the only
    memory surface that survives a clone.

    Unlike `get_review_context` there is no domain to narrow to, so the archive
    is capped by RECENCY instead: `pre_compact_hook.py` injects this string
    WHOLE and UNTRUNCATED into `additionalContext`, and the full archive is
    49526 of 51236 chars (~12400 tokens, measured 2026-08-03) -- a 30x increase
    delivered at the exact moment the session is compacting for lack of room.
    Reading the archive is the ticket; flooding the hook is not. Two review
    lenses flagged this independently and both were right: capping a regression
    introduced by this same change is mitigation, not new design.

    The cap keeps the NEWEST entries because compaction is about carrying the
    session forward, and it is deliberately generous -- it bounds the worst
    case without silently dropping memory in the common one.

    Note on precedence: dedup runs against L1 only. L2 is prose with no stable
    ``id``, so there is nothing to collide with.

    Before: Memory files may or may not exist.
    During: Reads the archive newest-first and caps it, then combines L3
            profile and L2 rules with a separator. Falls back to L1 raw
            observations if neither exists, applying per-ENTRY precedence (the
            live L1 copy wins on a stable-id collision, same rule as A1).
    After: Returns a markdown string with combined memory content.
    """
    archived = _cap_by_recency(_read_portable_archive(), _COMPACT_ARCHIVE_CAP)

    parts: list[str] = []

    profile = _try_read_file(_get_profile_file())
    if profile:
        parts.append(profile)

    rules = _try_read_file(_get_rules_file())
    if rules:
        parts.append(rules)

    if parts:
        local = "\n\n---\n\n".join(parts)
    else:
        observations = _read_observations()
        local = _format_observations_as_text(observations) if observations else ""
        if archived and observations:
            seen = {dedup_key(entry) for entry in observations}
            archived = [e for e in archived if dedup_key(e) not in seen]

    archive_text = _format_archive_as_text(archived)
    sections = [s for s in (archive_text, local) if s]
    return "\n\n".join(sections)


def _recallable_observations() -> list[dict[str, Any]]:
    """The pool `recall_observations` searches: live L1 + tracked archive.

    WOT-2026-047d: the twin of A1's fix, applied to the OTHER memory gate.
    `get_bootstrap_context` has read the portable archive since A1; recall did
    not, so the two doors disagreed about what memory exists. Measured on the
    real repo (2026-08-03): L1 held 427 entries of which 343 (80%) were
    `post_tool_hook` telemetry, while the tracked archive held 174 lessons and
    ZERO telemetry. They are not subsets -- recall reached none of the entries
    that actually travel between machines.

    Two filters, deliberately asymmetric:
      - Telemetry is dropped by PROVENANCE (`is_lesson`), never by label. It is
        80% of L1 and drowns the real lessons in any keyword query.
      - Precedence is per ENTRY, exactly as A1 does it: on a stable-``id``
        collision the LIVE L1 copy wins, because it may have been edited after
        being archived.

    Before: no state required; either source may be missing.
    During: reads all of L1 (limit=0) and every archive month; no writes.
    After: returns the union NEWEST-FIRST -- `_read_observations` is newest-first
        but the archive comes in file-and-line order (oldest first), so the pool
        is re-sorted by `timestamp` rather than concatenated. Never raises -- a
        corrupt archive degrades to L1 only (see `_read_portable_archive`).
    """
    live_all = _read_observations(limit=0)
    live = [obs for obs in live_all if is_lesson(obs)]
    archived = [obs for obs in _read_portable_archive() if is_lesson(obs)]

    if archived and live_all:
        # Dedup contra L1 COMPLETO, no contra `live` ya filtrado. Si una entrada
        # viva dejo de ser leccion (p.ej. se reescribio con un topic
        # autogenerado), sigue siendo la copia MAS RECIENTE de ese `id`:
        # deduplicar contra la lista filtrada la haria invisible en `seen` y el
        # archive REINTRODUCIRIA su version vieja. Es decir, la entrada
        # archivada y OBSOLETA resucitaria, que es justo lo contrario de la
        # precedencia por-entrada de A1.
        seen = {dedup_key(entry) for entry in live_all}
        archived = [e for e in archived if dedup_key(e) not in seen]

    # Orden NEWEST-FIRST sobre el pool unido. No es cosmetico: los consumidores
    # truncan con `limit` (`memory_context.py --recall` hace `[:limit]`), asi que
    # el orden decide QUE lecciones ve el agente. Concatenar `live + archived`
    # dejaba las 174 entradas del archive SIEMPRE detras de las vivas: con un
    # `--limit` pequeño volvian a ser inalcanzables -- el mismo fallo que este
    # ticket corrige, reintroducido por la puerta de atras.
    #
    # Medido el 2026-08-03: con los datos de HOY la concatenacion ya salia
    # ordenada por coincidencia (el L1 vivo filtrado queda casi vacio y domina
    # el archive). Ordenar es lo que convierte esa coincidencia en invariante.
    #
    # `timestamp` ausente ordena al final (cadena vacia), nunca reordena por
    # delante de una entrada fechada.
    return sorted(
        live + archived,
        key=lambda obs: str(obs.get("timestamp") or ""),
        reverse=True,
    )


def recall_observations(
    query: str | None = None,
    limit: int = _L1_FALLBACK_LIMIT,
) -> list[dict[str, Any]]:
    """Recall lessons from live L1 **and** the tracked portable archive.

    WOT-2026-047d: until this ticket the recall gate delegated entirely to
    `observations.jsonl` -- the gitignored buffer -- so the 174 lessons that
    travel by git were unreachable through it. See `_recallable_observations`
    for the measured numbers and the precedence rule.

    Before: Requires no state; neither source needs to exist.
    During: Builds the live+archive pool, optionally filters by keyword match
        on signal, topic or source.
    After: Returns a list of matching observation dicts (live entries first),
        or empty list. Never raises.
    """
    observations = _recallable_observations()

    if query:
        # Filter over the FULL pool, then truncate. Reading only a recent
        # window first (the pre-WOT-2026-021 behavior) made queries blind to
        # older observations even though they exist.
        query_lower = query.lower()
        filtered = []
        for obs in observations:
            signal = (obs.get("signal") or "").lower()
            topic = (obs.get("topic") or "").lower()
            source = (obs.get("source") or "").lower()
            if query_lower in signal or query_lower in topic or query_lower in source:
                filtered.append(obs)
        return filtered[:limit]

    return observations[:limit]


def get_memory_tier_status() -> dict[str, bool]:
    """Check which memory tiers are available.

    Before: Requires no state.
    During: Checks existence of each memory file.
    After: Returns dict with 'l3', 'l2', 'l1' keys indicating availability.
    """
    return {
        "l3": _get_profile_file().exists(),
        "l2": _get_rules_file().exists(),
        "l1": _get_observations_file().exists(),
    }
