#!/usr/bin/env python3
"""Central memory loader with L3 -> L2 -> L1 fallback hierarchy.

This module provides a single entry point for loading project memory
across the system (bootstrap, review bridge, pre-compact hook).

Memory hierarchy (loaded in order):
  L3 (memory_profile.md) — Brief, high-level project profile for quick context.
  L2 (memory_rules.md)   — Deterministic rules extracted by domain, parseable.
  L1 (observations.jsonl)— Raw observation records, limited to last N entries.

Usage:
    from bus.memory_loader import (
        get_bootstrap_context,
        get_review_context,
        get_compact_context,
        recall_observations,
    )

    ctx = get_bootstrap_context()  # L3 -> L2 -> L1 fallback
    review_ctx = get_review_context(domain="delivery-hygiene")
    compact_ctx = get_compact_context()
    obs = recall_observations(limit=10)

Design:
    - Fallthrough: each tier tries to load from its file; on failure or empty,
      it falls through to the next tier.
    - Deterministic: L2 and L3 files are regenerated by memory_consolidate.py
      and are deterministic given the same observations.jsonl.
    - Safe: never raises on missing/corrupted files; returns empty strings.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from runtime.project_root import get_agent_dir


# Default max observations when falling back to raw L1.
_L1_FALLBACK_LIMIT = 15


# --- Paths (computed lazily for testability) ---


def _get_memory_dir() -> Path:
    """Get the memory directory path.

    Before: Requires get_agent_dir() to be available.
    During: Computes path lazily each call (no caching) so tests can patch.
    After: Returns Path to .agent/runtime/memory/.
    """
    return get_agent_dir() / "runtime" / "memory"


def _get_observations_file() -> Path:
    """Get path to observations.jsonl."""
    return _get_memory_dir() / "observations.jsonl"


def _get_rules_file() -> Path:
    """Get path to memory_rules.md (L2)."""
    return _get_memory_dir() / "memory_rules.md"


def _get_profile_file() -> Path:
    """Get path to memory_profile.md (L3)."""
    return _get_memory_dir() / "memory_profile.md"


# --- Internal helpers ---


def _try_read_file(path: Path) -> str:
    """Read a text file safely, returning empty string on any error.

    Before: path must be a Path object.
    During: Reads the file with UTF-8 encoding, catching IOErrors.
    After: Returns file content as string, or '' if file missing/unreadable.
    """
    try:
        if path.exists():
            return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        pass
    return ""


def _read_observations(limit: int = _L1_FALLBACK_LIMIT) -> list[dict[str, Any]]:
    """Read the last N observations from observations.jsonl.

    Before: Requires observations.jsonl to exist (or returns empty list).
    During: Parses JSONL lines, keeping only valid dict entries.
            Reads from the end of the file to get the most recent entries.
    After: Returns a list of up to ``limit`` observation dicts, newest first.
    """
    obs_file = _get_observations_file()
    if not obs_file.exists():
        return []

    try:
        text = obs_file.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []

    lines = text.splitlines()
    # Read from end to collect the most recent entries
    observations: list[dict[str, Any]] = []
    for line in reversed(lines):
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
            if isinstance(entry, dict):
                observations.append(entry)
                if len(observations) >= limit:
                    break
        except json.JSONDecodeError:
            continue

    return observations


def _format_observations_as_text(observations: list[dict[str, Any]]) -> str:
    """Format a list of observation dicts as a markdown bullet list.

    Before: Requires a list of observation dicts (may be empty).
    During: Formats each entry as a bullet with timestamp, topic, signal, source.
    After: Returns a markdown string, or empty string if list is empty.
    """
    if not observations:
        return ""

    lines = [
        "# Raw Observations (L1 fallback)",
        "",
        f"Most recent {len(observations)} observations:",
        "",
    ]
    for obs in observations:
        ts = str(obs.get("timestamp") or "")[:19]
        topic = obs.get("topic", "general")
        signal = str(obs.get("signal") or "")[:200]
        source = obs.get("source", "unknown")
        lines.append(f"- [{ts}] **{topic}**: {signal} ({source})")

    return "\n".join(lines)


# --- Public API ---


def get_bootstrap_context() -> str:
    """Load context for bootstrap: L3 profile, falling back to L2, then L1.

    This is the primary entry point for session_bootstrap.md and any agent
    that needs a quick context summary of project memory.

    Before: Memory files may or may not exist in memory directory.
    During: Tries L3 (memory_profile.md), then L2 (memory_rules.md),
            then L1 raw observations (last _L1_FALLBACK_LIMIT entries).
    After: Returns a markdown string with the best available memory tier.
           Never returns None; returns empty string if no memory exists.
    """
    # Priority 1: L3 profile (brief, high-level)
    profile = _try_read_file(_get_profile_file())
    if profile:
        return profile

    # Priority 2: L2 rules (domain-organized rules)
    rules = _try_read_file(_get_rules_file())
    if rules:
        return rules

    # Priority 3: L1 fallback (last N raw observations)
    observations = _read_observations()
    if observations:
        return _format_observations_as_text(observations)

    return ""


def get_review_context(domain: str | None = None) -> str:
    """Load context for review: L2 rules filtered by domain, falling back to L1.

    Before: Requires optional domain string (e.g., 'delivery-hygiene').
    During: Tries L2 rules first. If a domain is specified, filters rules
            to that domain. Falls back to L1 raw observations if L2 is empty.
    After: Returns a markdown string with relevant rules or observations.
    """
    rules = _try_read_file(_get_rules_file())
    if not rules:
        observations = _read_observations()
        if observations:
            return _format_observations_as_text(observations)
        return ""

    if domain is None:
        return rules

    # Filter rules by domain
    filtered = _filter_rules_by_domain(rules, domain)
    if filtered:
        return filtered

    # No matching domain rules: return all rules as fallback
    return rules


def _has_wing_headers(rules_text: str) -> bool:
    """Check if the rules text uses the new Wing format (H2 Wing headers).

    Before: Requires the full text of memory_rules.md.
    During: Scans for ``## Wing:`` pattern.
    After: Returns True if Wing format detected, False otherwise.
    """
    return bool(re.search(r"^## Wing:\s+", rules_text, re.MULTILINE | re.IGNORECASE))


def _filter_rules_by_domain(rules_text: str, domain: str) -> str:
    """Filter memory_rules.md content to only include sections for a given domain.

    Before: Requires the full text of memory_rules.md and a domain string.
    During: Detects format (legacy H2 vs Wing H2/H3). Uses regex to find the
            matching ``## Domain: <domain>`` (legacy) or ``### Domain: <domain>``
            (Wing format) section and extract its content until the next Domain
            header or end of file.
    After: Returns the filtered section text, or empty string if domain not found.
            Retrocompat: if no Wing headers present, assumes legacy H2 format.
    """
    domain_lower = domain.lower()
    lines = rules_text.splitlines()

    # Detect format: Wing uses H3 (###), legacy uses H2 (##)
    has_wing = _has_wing_headers(rules_text)
    domain_pattern = r"^### Domain:\s*(.+)$" if has_wing else r"^## Domain:\s*(.+)$"
    domain_re = re.compile(domain_pattern, re.IGNORECASE)

    result_lines: list[str] = []
    in_target = False

    for line in lines:
        domain_match = domain_re.match(line)
        if domain_match:
            if in_target:
                break
            current_domain = domain_match.group(1).strip().lower()
            in_target = current_domain == domain_lower

        if in_target:
            result_lines.append(line)

    return "\n".join(result_lines).strip()


def get_compact_context() -> str:
    """Load combined context for pre-compact: L3 + L2, falling back to L1.

    Before: Memory files may or may not exist.
    During: Combines L3 profile and L2 rules with a separator.
            Falls back to L1 raw observations if neither exists.
    After: Returns a markdown string with combined memory content.
    """
    parts: list[str] = []

    profile = _try_read_file(_get_profile_file())
    if profile:
        parts.append(profile)

    rules = _try_read_file(_get_rules_file())
    if rules:
        parts.append(rules)

    if parts:
        return "\n\n---\n\n".join(parts)

    observations = _read_observations()
    if observations:
        return _format_observations_as_text(observations)

    return ""


def recall_observations(
    query: str | None = None,
    limit: int = _L1_FALLBACK_LIMIT,
) -> list[dict[str, Any]]:
    """Direct L1 recall from observations.jsonl with optional keyword filtering.

    Before: Requires no state; observations.jsonl may or may not exist.
    During: Reads observations, optionally filters by keyword match on signal.
    After: Returns a list of matching observation dicts (newest first), or empty list.
    """
    observations = _read_observations(limit=limit * 2)  # Read extra for filtering room

    if query:
        query_lower = query.lower()
        filtered = []
        for obs in observations:
            signal = (obs.get("signal") or "").lower()
            topic = (obs.get("topic") or "").lower()
            source = (obs.get("source") or "").lower()
            if query_lower in signal or query_lower in topic or query_lower in source:
                filtered.append(obs)
        return filtered[:limit]

    return observations[:limit]


def get_memory_tier_status() -> dict[str, bool]:
    """Check which memory tiers are available.

    Before: Requires no state.
    During: Checks existence of each memory file.
    After: Returns dict with 'l3', 'l2', 'l1' keys indicating availability.
    """
    return {
        "l3": _get_profile_file().exists(),
        "l2": _get_rules_file().exists(),
        "l1": _get_observations_file().exists(),
    }
