from __future__ import annotations

from pathlib import Path

import pytest
from scripts import check_hook_interpreter as chi


# A generated hook, faithful to what pre-commit emits (line 7 = INSTALL_PYTHON).
_HOOK_TEMPLATE = """#!/bin/sh
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON='{interpreter}'
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type={hook_type})
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${{ARGS[@]}}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${{ARGS[@]}}"
else
    echo '`pre-commit` not found.' 1>&2
    exit 1
fi
"""


def _write_hook(hooks_dir: Path, hook_type: str, interpreter: str) -> Path:
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / hook_type
    hook_path.write_text(
        _HOOK_TEMPLATE.format(interpreter=interpreter, hook_type=hook_type),
        encoding="utf-8",
    )
    return hook_path


def _existing_interpreter(tmp_path: Path) -> str:
    """A real path on disk that a hook can point at as its interpreter."""
    interp = tmp_path / "venv" / "Scripts" / "python.exe"
    interp.parent.mkdir(parents=True, exist_ok=True)
    interp.write_text("", encoding="utf-8")
    return str(interp)


def test_parse_install_python_single_and_double_quotes() -> None:
    assert (
        chi.parse_install_python("INSTALL_PYTHON='C:\\a\\python.exe'")
        == "C:\\a\\python.exe"
    )
    assert (
        chi.parse_install_python('INSTALL_PYTHON="C:\\b\\python.exe"')
        == "C:\\b\\python.exe"
    )


def test_parse_install_python_absent_returns_none() -> None:
    assert chi.parse_install_python("no interpreter line here\n") is None


@pytest.mark.parametrize("hook_type", chi.HOOK_TYPES)
def test_stale_interpreter_is_detected_per_hook_type(
    tmp_path: Path, hook_type: str
) -> None:
    """DoD #1 + #2: a hook whose INSTALL_PYTHON does not exist -> exit != 0,
    verified for pre-commit AND pre-push independently."""
    hooks_dir = tmp_path / ".git" / "hooks"
    missing = str(tmp_path / "z_scripts" / "gone" / "python.exe")  # never created
    _write_hook(hooks_dir, hook_type, missing)

    rc = chi.main(["--hooks-dir", str(hooks_dir)])
    assert rc == 1

    status = chi.check_hook(hooks_dir, hook_type)
    assert status.present is True
    assert status.interpreter == missing
    assert status.interpreter_ok is False
    assert status.stale is True


def test_existing_interpreter_passes(tmp_path: Path) -> None:
    """DoD #3 (PASS side): both hooks pointing at a real interpreter -> exit 0."""
    hooks_dir = tmp_path / ".git" / "hooks"
    interp = _existing_interpreter(tmp_path)
    for hook_type in chi.HOOK_TYPES:
        _write_hook(hooks_dir, hook_type, interp)

    assert chi.main(["--hooks-dir", str(hooks_dir)]) == 0


def test_absent_hook_is_not_a_false_positive(tmp_path: Path) -> None:
    """No hooks generated yet (empty dir) -> exit 0, not a spurious failure."""
    hooks_dir = tmp_path / ".git" / "hooks"
    hooks_dir.mkdir(parents=True)
    assert chi.main(["--hooks-dir", str(hooks_dir)]) == 0


def test_barrier_interpreter_existence_is_the_discriminant(tmp_path: Path) -> None:
    """DoD #3 (barrier): same hook text; only whether the interpreter exists on
    disk flips PASS<->FAIL, proving the check is not cosmetic."""
    hooks_dir = tmp_path / ".git" / "hooks"
    interp = _existing_interpreter(tmp_path)
    _write_hook(hooks_dir, "pre-commit", interp)

    # PASS-with: interpreter exists.
    assert chi.main(["--hooks-dir", str(hooks_dir)]) == 0

    # FAIL-without: delete the interpreter, hook text unchanged -> now stale.
    Path(interp).unlink()
    assert chi.main(["--hooks-dir", str(hooks_dir)]) == 1


def test_mixed_one_good_one_stale_still_fails(tmp_path: Path) -> None:
    """The live bug shape: pre-commit ok, pre-push stale -> the check must FAIL
    (must not 'pass' just because one hook is correct)."""
    hooks_dir = tmp_path / ".git" / "hooks"
    interp = _existing_interpreter(tmp_path)
    _write_hook(hooks_dir, "pre-commit", interp)
    _write_hook(
        hooks_dir, "pre-push", str(tmp_path / "z_scripts" / "gone" / "python.exe")
    )

    assert chi.main(["--hooks-dir", str(hooks_dir)]) == 1

    statuses = {s.hook_type: s for s in chi.check_all(hooks_dir)}
    assert statuses["pre-commit"].stale is False
    assert statuses["pre-push"].stale is True
