from __future__ import annotations

from pathlib import Path

import pytest
from scripts import check_hook_interpreter as chi


# A generated hook, faithful to what pre-commit emits (line 7 = INSTALL_PYTHON).
_HOOK_TEMPLATE = """#!/bin/sh
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON='{interpreter}'
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type={hook_type})
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${{ARGS[@]}}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${{ARGS[@]}}"
else
    echo '`pre-commit` not found.' 1>&2
    exit 1
fi
"""


def _write_hook(hooks_dir: Path, hook_type: str, interpreter: str) -> Path:
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / hook_type
    hook_path.write_text(
        _HOOK_TEMPLATE.format(interpreter=interpreter, hook_type=hook_type),
        encoding="utf-8",
    )
    return hook_path


def _existing_interpreter(tmp_path: Path) -> str:
    """A real path on disk that a hook can point at as its interpreter."""
    interp = tmp_path / "venv" / "Scripts" / "python.exe"
    interp.parent.mkdir(parents=True, exist_ok=True)
    interp.write_text("", encoding="utf-8")
    return str(interp)


def test_parse_install_python_single_and_double_quotes() -> None:
    assert (
        chi.parse_install_python("INSTALL_PYTHON='C:\\a\\python.exe'")
        == "C:\\a\\python.exe"
    )
    assert (
        chi.parse_install_python('INSTALL_PYTHON="C:\\b\\python.exe"')
        == "C:\\b\\python.exe"
    )


def test_parse_install_python_absent_returns_none() -> None:
    assert chi.parse_install_python("no interpreter line here\n") is None


@pytest.mark.parametrize("hook_type", chi.HOOK_TYPES)
def test_stale_interpreter_is_detected_per_hook_type(
    tmp_path: Path, hook_type: str
) -> None:
    """DoD #1 + #2: a hook whose INSTALL_PYTHON does not exist -> exit != 0,
    verified for pre-commit AND pre-push independently."""
    hooks_dir = tmp_path / ".git" / "hooks"
    missing = str(tmp_path / "z_scripts" / "gone" / "python.exe")  # never created
    _write_hook(hooks_dir, hook_type, missing)

    rc = chi.main(["--hooks-dir", str(hooks_dir)])
    assert rc == 1

    status = chi.check_hook(hooks_dir, hook_type)
    assert status.present is True
    assert status.interpreter == missing
    assert status.interpreter_ok is False
    assert status.stale is True


def test_existing_interpreter_passes(tmp_path: Path) -> None:
    """DoD #3 (PASS side): both hooks pointing at a real interpreter -> exit 0."""
    hooks_dir = tmp_path / ".git" / "hooks"
    interp = _existing_interpreter(tmp_path)
    for hook_type in chi.HOOK_TYPES:
        _write_hook(hooks_dir, hook_type, interp)

    assert chi.main(["--hooks-dir", str(hooks_dir)]) == 0


def test_absent_hook_is_not_a_false_positive(tmp_path: Path) -> None:
    """No hooks + repo does NOT declare hooks -> exit 0, not a spurious failure.

    WOT-2026-025d: the ``--repo-root`` is now an explicit config-less repo, so
    the "none present" PASS is only granted when the repo does not declare
    .pre-commit-config.yaml. A repo that declares hooks but installs none is a
    FAILURE (see test_declared_but_not_installed_fails).
    """
    repo_root = tmp_path / "repo"
    hooks_dir = repo_root / ".git" / "hooks"
    hooks_dir.mkdir(parents=True)
    assert chi.main(["--repo-root", str(repo_root), "--hooks-dir", str(hooks_dir)]) == 0


def test_barrier_interpreter_existence_is_the_discriminant(tmp_path: Path) -> None:
    """DoD #3 (barrier): same hook text; only whether the interpreter exists on
    disk flips PASS<->FAIL, proving the check is not cosmetic."""
    hooks_dir = tmp_path / ".git" / "hooks"
    interp = _existing_interpreter(tmp_path)
    _write_hook(hooks_dir, "pre-commit", interp)

    # PASS-with: interpreter exists.
    assert chi.main(["--hooks-dir", str(hooks_dir)]) == 0

    # FAIL-without: delete the interpreter, hook text unchanged -> now stale.
    Path(interp).unlink()
    assert chi.main(["--hooks-dir", str(hooks_dir)]) == 1


def test_mixed_one_good_one_stale_still_fails(tmp_path: Path) -> None:
    """The live bug shape: pre-commit ok, pre-push stale -> the check must FAIL
    (must not 'pass' just because one hook is correct)."""
    hooks_dir = tmp_path / ".git" / "hooks"
    interp = _existing_interpreter(tmp_path)
    _write_hook(hooks_dir, "pre-commit", interp)
    _write_hook(
        hooks_dir, "pre-push", str(tmp_path / "z_scripts" / "gone" / "python.exe")
    )

    assert chi.main(["--hooks-dir", str(hooks_dir)]) == 1

    statuses = {s.hook_type: s for s in chi.check_all(hooks_dir)}
    assert statuses["pre-commit"].stale is False
    assert statuses["pre-push"].stale is True


# ---- WOT-2026-025d: worktree fail-open ------------------------------------


def test_declared_but_not_installed_fails(tmp_path: Path) -> None:
    """DoD (b): a repo that DECLARES hooks (.pre-commit-config.yaml) but has
    none installed must FAIL, not PASS with '(none present)'."""
    repo_root = tmp_path / "repo"
    hooks_dir = repo_root / ".git" / "hooks"
    hooks_dir.mkdir(parents=True)
    (repo_root / ".pre-commit-config.yaml").write_text("repos: []\n", encoding="utf-8")

    rc = chi.main(["--repo-root", str(repo_root), "--hooks-dir", str(hooks_dir)])
    assert rc == 1, "declared-but-not-installed hooks must fail closed"


def _git(args: list[str], cwd: Path) -> None:
    import subprocess

    subprocess.run(
        ["git", *args],
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
    )


@pytest.mark.skipif(
    __import__("shutil").which("git") is None, reason="git not available"
)
def test_default_hooks_dir_resolves_through_worktree_gitlink(tmp_path: Path) -> None:
    """DoD (c) + (d): from a linked worktree, .git is a FILE (gitlink), so the
    literal <worktree>/.git/hooks does NOT exist. _default_hooks_dir must
    resolve via `git rev-parse --git-path hooks` to the common hooks dir, so the
    check SEES the hooks instead of fail-open '(none present)'.

    Mutation: revert _default_hooks_dir to `repo_root / '.git' / 'hooks'` and
    this test fails, because the literal path in a worktree is not a directory.
    """
    main_repo = tmp_path / "main"
    main_repo.mkdir()
    _git(["init"], main_repo)
    _git(["config", "user.email", "t@t.t"], main_repo)
    _git(["config", "user.name", "t"], main_repo)
    (main_repo / "f.txt").write_text("x\n", encoding="utf-8")
    _git(["add", "f.txt"], main_repo)
    _git(["commit", "-m", "init"], main_repo)

    worktree = tmp_path / "wt"
    _git(["worktree", "add", str(worktree)], main_repo)

    # In the worktree, .git is a FILE (gitlink), not a dir.
    assert (worktree / ".git").is_file()
    literal_join = worktree / ".git" / "hooks"
    assert not literal_join.is_dir(), "the literal join must NOT resolve in a worktree"

    # The fix: _default_hooks_dir resolves to the REAL (common) hooks dir.
    resolved = chi._default_hooks_dir(worktree.resolve())
    assert resolved.is_dir(), (
        "worktree-safe hooks dir must exist (git rev-parse --git-path hooks); "
        f"got {resolved}"
    )
    # The common hooks dir lives under the MAIN repo's .git, not the worktree.
    assert "hooks" in resolved.name


@pytest.mark.skipif(
    __import__("shutil").which("git") is None, reason="git not available"
)
def test_main_from_worktree_sees_installed_hooks_e2e(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """WOT-2026-025l (F3 audit): END-TO-END. Run main() FROM a linked worktree
    (no --hooks-dir) with real hooks installed in the shared common dir, and
    require the OUTPUT to SEE them (pre-commit, pre-push) -- not the fail-open
    "(none present)".

    The sibling test above only calls _default_hooks_dir() directly; it never
    runs main()'s resolve+report path from the worktree, so the behaviour the
    docstring promises ("the check SEES the hooks") was never exercised e2e.

    Mutation (teeth): revert _default_hooks_dir to `repo_root / ".git" / "hooks"`
    and this test FAILS -- from a worktree `.git` is a gitlink FILE, so the
    literal join does not exist and the check reports "(none present)" instead
    of seeing the hooks.
    """
    import subprocess

    main_repo = tmp_path / "main"
    main_repo.mkdir()
    _git(["init"], main_repo)
    _git(["config", "user.email", "t@t.t"], main_repo)
    _git(["config", "user.name", "t"], main_repo)
    (main_repo / "f.txt").write_text("x\n", encoding="utf-8")
    _git(["add", "f.txt"], main_repo)
    _git(["commit", "-m", "init"], main_repo)

    worktree = tmp_path / "wt"
    _git(["worktree", "add", str(worktree)], main_repo)

    # Resolve the SHARED common hooks dir via git itself (independent oracle,
    # NOT the function under test) and install real hooks there.
    proc = subprocess.run(
        ["git", "-C", str(worktree), "rev-parse", "--git-path", "hooks"],
        check=True,
        capture_output=True,
        text=True,
    )
    common_hooks = Path(proc.stdout.strip())
    if not common_hooks.is_absolute():
        common_hooks = (worktree / common_hooks).resolve()

    interp = _existing_interpreter(tmp_path)
    for hook_type in chi.HOOK_TYPES:
        _write_hook(common_hooks, hook_type, interp)

    # Run main() FROM the worktree; _default_hooks_dir must resolve the shared dir.
    rc = chi.main(["--repo-root", str(worktree)])
    out = capsys.readouterr().out

    assert rc == 0, f"expected PASS from worktree, got rc={rc}; out={out!r}"
    assert "none present" not in out, (
        f"check fell open to '(none present)' from the worktree; out={out!r}"
    )
    assert "pre-commit" in out and "pre-push" in out, (
        f"check did not SEE both hooks from the worktree common dir; out={out!r}"
    )
