#!/usr/bin/env python3
"""
Guard: lecciones portables que se creen promovidas y NO van a viajar (WOT-2026-022z).

QUE DETECTA
-----------
Un record de LECCION (topic fuera de AUTOGENERATED_TOPICS) presente en el
`observations.jsonl` de runtime y AUSENTE de TODOS los `archive/*.jsonl`.

`.agent/runtime/memory/observations.jsonl` esta GITIGNORED (.gitignore:104) en TODAS las
worktrees: escribir ahi NO promueve nada, ningun push lo mueve. El unico vehiculo portable
es el ARCHIVE TRACKEADO `.agent/runtime/memory/archive/observations.YYYY-MM.jsonl`. Una
leccion que solo existe en el runtime es una leccion HUERFANA: la sesion cree haberla
promovido y jamas sale de la maquina.

POR QUE ES UN SCRIPT PROPIO Y NO UN FAIL-CLOSED EN append_observation()
-----------------------------------------------------------------------
`.agent/runtime/memory/memory_helpers.py::append_observation` lo usan los HOOKS DE RUNTIME
(`.agent/hooks/post_tool_hook.py`, en CADA tool call) y `scripts/session_close_observations.py`
(en cada cierre). Un fail-closed ahi ROMPERIA el trabajo normal. Telemetria efimera y leccion
portable comparten fichero Y writer: el eje que separa una de otra es QUE se escribe (el
topic), no desde donde. Por eso el guard es READ-ONLY y se invoca en el CIERRE.

EXIT CODES (diferenciados a proposito: "hay huerfanas" != "la herramienta esta rota")
-------------------------------------------------------------------------------------
- 0: sin huerfanas (o no hay memoria runtime que revisar).
- 1: la HERRAMIENTA fallo (no es un repo git, fichero ilegible, JSON corrupto...).
- 4: HAY HUERFANAS. Es un hallazgo, no un error de la herramienta.

Uso:
    python scripts/check_portable_memory_promotion.py --project-root <repo>

Remedio (depende de la topologia, WOT-2026-038j; politica actualizada por
WOT-2026-026f / DEC-026F-001):
- Worktree NO canonica: `python scripts/reconcile_portable_memory.py --source <worktree>
  --apply` + commit del archive.
- Checkout canonico / repo_destino independiente (source==dest, donde ese comando A SECAS
  seria NO-OP). DOS vias legitimas, ninguna sustituye a la otra:
  (A) VIA CURADA (explicita, para promover UNA leccion valiosa YA):
      `python scripts/reconcile_portable_memory.py --source <repo> --promote-id <id>
      --apply`. Confirmacion humana + `validate_observations --strict` antes y despues +
      dedup por id. Es la via que formaliza `prompts/memory_upload.md`.
  (B) VIA AUTOMATICA (rutinaria, por ANTIGUEDAD): `memory_consolidate` promueve cuando la
      leccion cruza el cutoff de 30 dias, en un closeout SIN --skip-slow.
  En ambas: commit del archive, o la promocion no viaja.

NO es cierto que "una leccion RECIENTE no se pueda forzar" (clausula retirada): no se
promueve por ANTIGUEDAD, pero SI por la via curada. Medido 2026-07-21: 2 lecciones de 45
minutos promovidas -> `--strict` exit 0, 0 huerfanas, commit 0562f78.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parent))
# Reutiliza la canonicalizacion del PROPIO reconciliador (misma fuente de verdad sobre
# "esta worktree es su checkout canonico"). No se re-implementa la deteccion: si el
# reconciliador cambia de criterio, el guard lo sigue automaticamente (WOT-2026-038j).
from reconcile_portable_memory import is_canonical


OBS_REL = Path(".agent/runtime/memory/observations.jsonl")
ARCHIVE_DIR_REL = Path(".agent/runtime/memory/archive")

# Telemetria emitida por scripts/session_close_observations.py en cada cierre. NO son
# lecciones portables: no deben viajar, asi que su ausencia del archive NO es huerfandad.
AUTOGENERATED_TOPICS = frozenset({"architecture", "ticket-completion"})

EXIT_OK = 0
EXIT_TOOL_ERROR = 1
EXIT_ORPHANS = 4


class ToolError(Exception):
    """Fallo de la HERRAMIENTA (exit 1), distinto de un hallazgo (exit 4)."""


def record_key(record: dict) -> tuple[str, str | None]:
    """Identidad: (topic, source_ticket). NUNCA `topic` a secas: es una etiqueta
    generica reutilizada por decenas de records, uno por ticket."""
    return (record.get("topic", ""), record.get("source_ticket"))


def is_lesson(record: dict) -> bool:
    return record.get("topic") not in AUTOGENERATED_TOPICS


def load_records(path: Path) -> list[dict]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ToolError(f"no se puede leer {path}: {exc}") from exc

    records = []
    for num, line in enumerate(text.splitlines(), start=1):
        if not line.strip():
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError as exc:
            raise ToolError(f"{path}:{num}: JSON invalido: {exc}") from exc
    return records


def assert_git_repo(root: Path) -> None:
    """`root` debe ser la RAIZ (toplevel) de un checkout/worktree, no un subdirectorio
    cualquiera dentro de uno.

    "Estar dentro de un repo git" NO basta: un directorio suelto creado bajo el arbol del
    motor (p.ej. el sandbox de tests) responde a `rev-parse --git-dir` con el .git DEL
    MOTOR -> el guard auditaria la memoria de un path que no es un repo y lo daria por
    bueno. Se exige toplevel == root.
    """
    r = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],  # noqa: S607
        cwd=str(root),
        capture_output=True,
        text=True,
        check=False,
    )
    if r.returncode != 0:
        raise ToolError(f"{root} no es un repositorio git (returncode={r.returncode})")
    toplevel = Path(r.stdout.strip()).resolve()
    if toplevel != root:
        raise ToolError(
            f"--project-root debe ser la raiz de un checkout git; {root} esta DENTRO "
            f"de {toplevel} pero no es su raiz"
        )


def archived_keys(root: Path) -> set[tuple[str, str | None]]:
    """Claves presentes en CUALQUIER archive/*.jsonl (todos los meses, no solo el
    actual: una leccion promovida en junio ya viajo)."""
    archive_dir = root / ARCHIVE_DIR_REL
    if not archive_dir.is_dir():
        return set()
    keys: set[tuple[str, str | None]] = set()
    for path in sorted(archive_dir.glob("observations.*.jsonl")):
        keys.update(record_key(r) for r in load_records(path))
    return keys


def find_orphans(root: Path) -> list[dict]:
    """Lecciones en el runtime observations.jsonl ausentes de TODO el archive."""
    obs = root / OBS_REL
    if not obs.is_file():
        return []
    archived = archived_keys(root)
    return [
        r for r in load_records(obs) if is_lesson(r) and record_key(r) not in archived
    ]


def _print_remedy(root: Path) -> None:
    """Imprime el remedio APLICABLE a la topologia de `root` (WOT-2026-038j).

    El remedio historico (`reconcile_portable_memory --source <worktree> --apply`) SOLO
    promueve algo cuando `root` es una worktree NO canonica: el reconciliador calcula
    `dest = canonical_checkout(source)` y RETORNA NO-OP si `source == dest`
    (reconcile_portable_memory.py:276-278). En un repo_destino independiente -- que es su
    PROPIO checkout canonico -- ese comando sale exit 0 sin escribir nada. Dirigir ahi al
    operador es la trampa del "exit 0 = no hice nada" DENTRO de la barrera que existe para
    evitarla. Por eso se ramifica por `is_canonical`, reutilizando la canonicalizacion del
    propio reconciliador (misma fuente de verdad, sin heuristica nueva).

    WOT-2026-026f / DEC-026F-001 (politica B1) -- ACTUALIZA 038j: la version previa de
    esta rama declaraba que "una leccion RECIENTE NO se puede forzar: espera a que cruce
    el umbral". Eso contradecia a `prompts/memory_upload.md`, que exige promover con
    CONFIRMACION HUMANA explicita y sin mencion de cutoff; y la contradiccion se resolvio
    MIDIENDO: el 2026-07-21 se promovieron 2 lecciones de 45 MINUTOS escribiendo al
    archive trackeado y el resultado fue PERFECTAMENTE VALIDO (`validate_observations
    --strict` exit 0, 0 huerfanas, commit 0562f78). O sea: la via que 038j declaraba
    imposible producia estado valido. La clausula correcta es "no se promueve POR
    ANTIGUEDAD; usa la via curada explicita".

    Contrato mutuo (D3): esta rama y `prompts/memory_upload.md` se CITAN entre si para no
    volver a divergir. Las DOS vias son legitimas:
      (A) curada    -> `reconcile_portable_memory.py --promote-id <id> --apply`
      (B) antiguedad -> `memory_consolidate.py --apply` (cutoff 30d)
    """
    if is_canonical(root):
        print(
            "[promotion-guard] REMEDIO (este repo ES su checkout canonico: "
            "`reconcile --source <este repo> --apply` A SECAS seria NO-OP, source==dest):"
        )
        print(
            "[promotion-guard]   (A) VIA CURADA -- promueve UNA leccion concreta YA, sin "
            "esperar al cutoff (WOT-2026-026f / DEC-026F-001):"
        )
        print(
            "[promotion-guard]       python scripts/reconcile_portable_memory.py "
            "--source <este repo> --promote-id <id> --apply"
        )
        print(
            "[promotion-guard]       (dry-run sin --apply; valida --strict antes y "
            "despues; dedup por id. El `id` es el campo `id` del record)."
        )
        print(
            "[promotion-guard]   (B) VIA AUTOMATICA -- por ANTIGUEDAD: memory_consolidate "
            "promueve una leccion cuando su timestamp supera"
        )
        print(
            "[promotion-guard]       el cutoff de 30 dias (split_by_age, "
            "memory_consolidate.py:144-160):"
        )
        print("[promotion-guard]       python scripts/memory_consolidate.py --apply")
        print(
            "[promotion-guard]   Una leccion RECIENTE no se promueve POR ANTIGUEDAD "
            "(hay que esperar), pero SI por la via curada (A)."
        )
        print(
            f"[promotion-guard]   En ambos casos COMMITEA {ARCHIVE_DIR_REL.as_posix()}: "
            "sin commit la promocion no viaja."
        )
    else:
        print(
            "[promotion-guard] REMEDIO: python scripts/reconcile_portable_memory.py "
            "--source <worktree> --apply"
        )
        print(
            f"[promotion-guard] y COMMITEA {ARCHIVE_DIR_REL.as_posix()}: "
            "sin commit la promocion no existe."
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument(
        "--project-root",
        "--repo",
        dest="project_root",
        required=True,
        help="raiz del repo a auditar (sin fallback silencioso al cwd: un cwd "
        "heredado auditaria el repo equivocado y daria un falso-verde)",
    )
    args = parser.parse_args(argv)

    root = Path(args.project_root).resolve()

    try:
        if not root.is_dir():
            raise ToolError(f"--project-root no existe: {root}")
        assert_git_repo(root)
        orphans = find_orphans(root)
    except ToolError as exc:
        print(f"[promotion-guard] ERROR DE HERRAMIENTA: {exc}", file=sys.stderr)
        return EXIT_TOOL_ERROR

    print(f"[promotion-guard] repo: {root}")

    if not orphans:
        print("[promotion-guard] OK: ninguna leccion huerfana")
        print(
            "[promotion-guard] (toda leccion del runtime esta en el archive trackeado)"
        )
        return EXIT_OK

    print(
        f"[promotion-guard] HUERFANAS: {len(orphans)} leccion(es) en "
        f"{OBS_REL.as_posix()} (GITIGNORED) y AUSENTES del archive trackeado."
    )
    print("[promotion-guard] Estas lecciones NO viajan: ningun push las mueve.")
    for r in orphans:
        print(
            f"[promotion-guard]   - {r.get('topic')} "
            f"(source_ticket={r.get('source_ticket')})"
        )
    _print_remedy(root)
    return EXIT_ORPHANS


if __name__ == "__main__":
    raise SystemExit(main())
