#!/usr/bin/env python3
"""
Loop Registry Discovery -- reads the citable ensemble loop/backend registry.

WOT-2026-037b: single anti-drift source of truth for ensemble governance
loops and backend keys lives in ``.agent/config/agents.json::ensemble_registry``.
This script is the read-only discovery surface over that source, mirroring
the pattern of ``scripts/discover_skills.py`` (frontmatter-driven discovery
for skills; here, JSON-driven discovery for loops/backends).

Docstring-as-Spec (AGENTS.md):
  Before: ``.agent/config/agents.json`` exists and is valid JSON. It may or
          may not contain the ``ensemble_registry`` top-level key (older
          schema versions do not; this script tolerates absence and returns
          an empty projection rather than raising).
  During: Loads the JSON file once, extracts ``ensemble_registry`` (or an
          empty skeleton if missing), and derives a machine map of
          ``loop_ids`` and ``backend_keys``. No writes, no mutation of the
          source file. ``--generate`` derives and writes the markdown
          projection to ``docs/registry/loop_registry.md``; ``--check``
          verifies the on-disk markdown matches the live projection without
          writing.
  After: ``--json`` prints a machine-readable map to stdout and exits 0.
         ``--generate``/``--check`` exit 0 on success; ``--check`` exits 1
         if the markdown is stale or missing. Any JSON parse error on the
         config file propagates as an uncaught exception (fail-closed: a
         malformed source must not silently report an empty registry).
"""

import json
import sys
from pathlib import Path
from typing import Any


def _get_bundle_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _config_path(bundle_root: Path | None = None) -> Path:
    root = bundle_root or _get_bundle_root()
    return root / ".agent" / "config" / "agents.json"


EMPTY_REGISTRY: dict[str, Any] = {
    "backend_keys": {},
    "loop_shapes": {},
    "statuses": [],
}


def load_registry(config_path: Path | None = None) -> dict[str, Any]:
    """Load ``ensemble_registry`` from agents.json.

    Returns the ``EMPTY_REGISTRY`` skeleton if the key is absent (older
    schema versions). Raises ``json.JSONDecodeError`` on malformed JSON and
    ``FileNotFoundError`` if the config file does not exist -- both are
    fail-closed, not silently swallowed.
    """
    path = config_path or _config_path()
    with open(path, encoding="utf-8") as f:
        config = json.load(f)
    registry = config.get("ensemble_registry")
    if registry is None:
        return dict(EMPTY_REGISTRY)
    return registry


def discover_loops(config_path: Path | None = None) -> dict[str, Any]:
    """Derive the machine map of loop_ids and backend_keys from the registry.

    Returns a dict with ``loop_ids`` (sorted list of L### keys),
    ``backend_keys`` (sorted list of BA## keys), ``loop_shapes`` and
    ``backend_key_details`` (the full registry sub-dicts, for consumers that
    need more than the id lists), and ``statuses`` (the allowed enum).
    """
    registry = load_registry(config_path)
    loop_shapes = registry.get("loop_shapes", {})
    backend_keys = registry.get("backend_keys", {})
    return {
        "loop_ids": sorted(loop_shapes.keys()),
        "backend_keys": sorted(backend_keys.keys()),
        "loop_shapes": loop_shapes,
        "backend_key_details": backend_keys,
        "statuses": registry.get("statuses", []),
    }


# --------------------------------------------------------------------------
# Generated markdown projection (docs/registry/loop_registry.md).
# Mirrors discover_skills.py's render_index()/generate_index()/check pattern:
# authority stays in agents.json::ensemble_registry; the .md is a derived,
# regenerable projection. Never hand-edit the .md.
# --------------------------------------------------------------------------

REGISTRY_REL_PATH = "docs/registry/loop_registry.md"
REGISTRY_AUTOGEN_MARKER = "<!-- AUTOGENERATED by discover_loops.py --generate"


def render_registry_md(result: dict[str, Any]) -> str:
    """Render the loop_registry.md projection from a discover_loops() result.

    Deterministic: same input always yields the same string (stable sort
    keys throughout), which is what the parity seam-guard test relies on.
    """
    lines: list[str] = [
        f"{REGISTRY_AUTOGEN_MARKER}; do not edit by hand (WOT-2026-037b). -->",
        "# Registro de bucles de ensemble (proyeccion generada)",
        "",
        "> Proyeccion generada por `discover_loops.py --generate`.",
        "> Autoridad: `.agent/config/agents.json::ensemble_registry`. Este",
        "> archivo NO es fuente de verdad; regeneralo con",
        "> `python scripts/discover_loops.py --generate`.",
        "",
        "## Que significa cada `status` (y que NO significa)",
        "",
        "> Enum del registro de BACKENDS, que vive en",
        "> `.agent/config/agents.json` -> `ensemble_registry.statuses`:",
        "> `active` / `deprecated` / `archived`. NO es el enum del catalogo de",
        "> SKILLS (`active`/`deprecated`/`draft`, ver `docs/registry/README.md`):",
        "> son catalogos distintos con nombres que colisionan. Antes de cambiar un",
        "> `status`, confirma en cual de los dos estas.",
        "",
        "| status | significa | NO significa |",
        "|--------|-----------|--------------|",
        "| `active` | el backend esta EN USO: puede figurar en un `loop_shape` "
        "y se lanza. | que responda siempre. Un backend activo puede fallar una "
        "corrida, o varias, y seguir activo. |",
        "| `deprecated` | ya no es recomendable para uso NUEVO: obsolescencia, "
        "sustituto mejor, retirada del proveedor, licencia, seguridad, coste o "
        "cumplimiento. Ej. `BA14 = deepseek-v4-flash-0731`, superado por "
        "`deepseek-v4-flash`. Puede seguir en un `loop_shape` mientras se migra. | "
        "que este caido ni que haya fallado. Es un juicio sobre su VIGENCIA, no "
        "sobre su disponibilidad. |",
        "| `archived` | retiro DELIBERADO del catalogo operativo; se conserva por "
        "trazabilidad historica. | que estuviera roto o caido. No se usa para "
        "expulsar un backend que falla: eso seria un `deprecated` silencioso. |",
        "",
        "### Regla operativa: que cambia un `status` y que NO",
        "",
        "**Ningun fallo de ejecucion cambia un `status`.** Ni `transport-failed`, "
        "ni timeout, ni un smoke en rojo, ni una sesion entera sin respuesta. Esos "
        "se registran como INCIDENTE o deuda, y el backend sigue `active`.",
        "",
        "Para mover un backend fuera de `active` hace falta evidencia que EXCLUYA "
        "lo temporal: causa documentada (el proveedor lo retiro, hay sustituto, "
        "vencio la licencia) o un patron sostenido a lo largo de VARIAS sesiones. "
        "Con evidencia de una sola sesion, sigue `active`.",
        "",
        "Y como cualquier `status` distinto de `active` puede sacar al backend de "
        "los bucles adversariales, el cambio declara que FAMILIA DE LENTE se "
        "pierde y si la cobertura restante sigue siendo suficiente.",
        "",
        "**Caso medido (2026-09-04):** se marco `BA05` (codex) como `deprecated` "
        "tras 3 `transport-failed` en UNA sesion, y eso lo saco de todos los "
        "bucles. Era un fallo TEMPORAL: el mismo backend entrego despues una "
        'auditoria completa. Confundir "no respondio hoy" con "esta obsoleto" '
        "degrada el gobierno adversarial EN SILENCIO -- se pierde una familia de "
        "lente y ningun gate lo detecta, porque el registro queda internamente "
        "coherente. Lo cazo el usuario, no un mecanismo.",
        "",
        "**El fallo cronico SI tiene salida, y no es `deprecated`:** un backend "
        "cuyo endpoint desaparecio o que lleva meses sin responder se `archived` "
        "con su evidencia. `deprecated` habla de vigencia; `archived`, de retiro.",
        "",
        "**Antes de culpar al backend, descarta el instrumento.** Si el smoke "
        "devuelve `alive: true` sin el `PONG` esperado, el defecto es del "
        "DISPATCHER: abrelo como tal y deja el `status` intacto. La salud del "
        "backend es la ULTIMA hipotesis, no la primera.",
        "",
        "## Backend keys",
        "",
        "| backend_key | backend | model | status |",
        "|-------------|---------|-------|--------|",
    ]
    for key in sorted(result["backend_key_details"].keys()):
        entry = result["backend_key_details"][key]
        model = entry.get("model") or "—"
        lines.append(
            f"| {key} | {entry.get('backend', '')} | {model} "
            f"| {entry.get('status', '')} |"
        )

    lines += [
        "",
        "## Loop shapes",
        "",
        "| loop_id | name | launched_from | steps | status |",
        "|---------|------|----------------|-------|--------|",
    ]
    for loop_id in sorted(result["loop_shapes"].keys()):
        shape = result["loop_shapes"][loop_id]
        step_count = len(shape.get("steps", []))
        lines.append(
            f"| {loop_id} | {shape.get('name', '')} "
            f"| {shape.get('launched_from', '')} | {step_count} "
            f"| {shape.get('status', '')} |"
        )

    lines += ["", "## Steps by loop", ""]
    for loop_id in sorted(result["loop_shapes"].keys()):
        shape = result["loop_shapes"][loop_id]
        lines.append(f"### {loop_id} ({shape.get('name', '')})")
        lines.append("")
        lines.append("| phase | function | backend_key |")
        lines.append("|-------|----------|-------------|")
        for step in shape.get("steps", []):
            lines.append(
                f"| {step.get('phase', '')} | {step.get('function', '')} "
                f"| {step.get('backend_key', '')} |"
            )
        lines.append("")

    return "\n".join(lines)


def _registry_md_path(bundle_root: Path | None = None) -> Path:
    root = bundle_root or _get_bundle_root()
    return root / REGISTRY_REL_PATH


def generate_registry_md(
    config_path: Path | None = None, bundle_root: Path | None = None
) -> Path:
    """Generate docs/registry/loop_registry.md from the live registry. Returns its path."""
    result = discover_loops(config_path)
    out_path = _registry_md_path(bundle_root)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_registry_md(result), encoding="utf-8")
    return out_path


def check_registry_md_stale(
    config_path: Path | None = None, bundle_root: Path | None = None
) -> tuple[bool, str]:
    """Check whether loop_registry.md matches the live registry projection.

    Returns (is_stale, diagnostic). is_stale is True when the file is
    missing or diverges from the freshly-derived projection.
    """
    result = discover_loops(config_path)
    expected = render_registry_md(result)
    out_path = _registry_md_path(bundle_root)
    if not out_path.exists():
        return True, f"{REGISTRY_REL_PATH} does not exist; run --generate."
    actual = out_path.read_text(encoding="utf-8")
    if actual != expected:
        return True, (
            f"{REGISTRY_REL_PATH} is stale vs the live ensemble_registry. "
            "Regenerate with: python scripts/discover_loops.py --generate"
        )
    return False, ""


def main() -> None:
    """CLI entry point."""
    if "--generate" in sys.argv:
        path = generate_registry_md()
        print(f"[OK] Generated {path.relative_to(_get_bundle_root())}")
        return

    if "--check" in sys.argv:
        is_stale, diag = check_registry_md_stale()
        if is_stale:
            print(f"[STALE] {diag}", file=sys.stderr)
            raise SystemExit(1)
        print("[OK] loop_registry.md is in sync with the live ensemble_registry.")
        return

    result = discover_loops()

    if "--json" in sys.argv:
        print(json.dumps(result, indent=2, ensure_ascii=False))
        return

    print("\nLOOP REGISTRY DISCOVERY RESULTS\n")
    print(f"Loop shapes: {len(result['loop_ids'])}")
    print(f"Backend keys: {len(result['backend_keys'])}\n")
    if result["loop_ids"]:
        print("| loop_id | name | launched_from |")
        print("|---------|------|----------------|")
        for loop_id in result["loop_ids"]:
            shape = result["loop_shapes"][loop_id]
            print(
                f"| {loop_id} | {shape.get('name', '')} | {shape.get('launched_from', '')} |"
            )
    else:
        print("No loop shapes found in ensemble_registry")


if __name__ == "__main__":
    main()
