#!/usr/bin/env python3
"""
Reconciliador de memoria portable del motor entre worktrees (WOT-2026-022y).

EL PROBLEMA
-----------
`.agent/runtime/memory/observations.jsonl` es contenido del ARBOL DE TRABAJO, no
metadatos de git, y esta gitignored. Por tanto NO se comparte entre worktrees: cada
worktree tiene su propio fichero, y ningun push los reconcilia. Escribir memoria
portable desde una worktree NO canonica (p.ej. `_dev`) PARECE una promocion y no lo
es: la leccion nunca llega al checkout canonico. La perdida es silenciosa.

Evidencia que motivo el script (2026-07-12): la worktree de desarrollo acumulaba 7
lecciones manuales que jamas llegaron al canonico, varias de ellas registradas en el
indice de memoria como "portables" -- sesiones previas creyeron promoverlas.

QUE RECONCILIA (y que NO)
-------------------------
Solo se promueven las observaciones ESCRITAS A MANO. Los topics de la lista
AUTOGENERATED_TOPICS los emite `scripts/session_close_observations.py` en CADA cierre
de sesion (telemetria mecanica: "Ticket X completado: ...", "Decisiones
arquitectonicas documentadas en X"). El checkout canonico ya acumula los suyos, asi
que copiarlos desde otra worktree solo ensuciaria la memoria con ruido -- e incluso
con registros vacios ("completado: Unknown"). Se EXCLUYEN por diseno.

IDENTIDAD DEL RECORD
--------------------
La clave es `(topic, source_ticket)`, NUNCA `topic` a secas: `topic` es una etiqueta
generica reutilizada (p.ej. "architecture" tiene decenas de records, uno por ticket).
Deduplicar por `topic` descartaria records legitimos como si fueran duplicados.

Una clave que ya existe en el destino NO se sobrescribe: se reporta como colision para
decision humana (nunca un merge a ciegas).

Uso:
    python scripts/reconcile_portable_memory.py --source <worktree> [--apply]

Sin `--apply` es un DRY-RUN (read-only): enumera lo que promoveria y no escribe nada.

Salida:
- Exit 0: reconciliacion correcta (o dry-run limpio).
- Exit 1: el destino no es el checkout canonico, o `validate_observations --strict`
  falla antes/despues de escribir (fail-closed: no se deja memoria invalida).
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


OBS_REL = Path(".agent/runtime/memory/observations.jsonl")

# Topics emitidos automaticamente por scripts/session_close_observations.py en cada
# cierre. NO son lecciones: son telemetria. El canonico ya genera los suyos.
AUTOGENERATED_TOPICS = frozenset({"architecture", "ticket-completion"})


def _git(repo: Path, *args: str) -> str:
    r = subprocess.run(  # noqa: S603
        ["git", *args],  # noqa: S607
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=False,
    )
    return r.stdout.strip()


def canonical_checkout(repo: Path) -> Path:
    """La raiz del checkout CANONICO del repo que contiene `repo`.

    Se resuelve por `--git-common-dir` (el `.git` REAL, compartido por todas las
    worktrees): su directorio padre es el checkout canonico. Es robusto, a diferencia
    de heuristicas sobre la cadena del `--git-dir` (buscar "worktrees/" en el path
    funciona por accidente de nombres, no por construccion).
    """
    raw = Path(_git(repo, "rev-parse", "--git-common-dir"))
    # `--git-common-dir` puede venir RELATIVO (p.ej. ".git" en el propio canonico).
    # Un `.resolve()` directo lo resolveria contra el CWD DEL PROCESO, no contra el
    # repo -> raiz equivocada. Hay que anclarlo al repo.
    common = raw if raw.is_absolute() else (repo / raw)
    return common.resolve().parent


def is_canonical(repo: Path) -> bool:
    toplevel = Path(_git(repo, "rev-parse", "--show-toplevel")).resolve()
    return toplevel == canonical_checkout(repo)


def load_records(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def record_key(record: dict) -> tuple[str, str | None]:
    return (record.get("topic", ""), record.get("source_ticket"))


def is_lesson(record: dict) -> bool:
    return record.get("topic") not in AUTOGENERATED_TOPICS


def validate_strict(motor_root: Path, target_root: Path) -> int:
    """Devuelve el returncode REAL de `validate_observations.py --strict` sobre el
    fichero de observaciones DE `target_root`.

    `--file` es OBLIGATORIO aqui: el validador resuelve su fichero por defecto con
    `Path(__file__).parent.parent` (el repo DEL SCRIPT), ignorando el `cwd`. Lanzarlo
    con `cwd=target_root` y sin `--file` validaria SIEMPRE la memoria del motor y
    devolveria 0 aunque la del destino estuviese corrupta: un falso-verde que anula
    la barrera fail-closed entera.

    Nunca leer `$?` tras un pipe: seria el exit del ultimo comando de la tuberia.
    """
    r = subprocess.run(  # noqa: S603
        [
            sys.executable,
            str(motor_root / "scripts" / "validate_observations.py"),
            "--strict",
            "--file",
            str(target_root / OBS_REL),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    return r.returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument(
        "--source", required=True, help="worktree cuya memoria se reconcilia"
    )
    parser.add_argument(
        "--apply", action="store_true", help="escribir (por defecto: dry-run)"
    )
    args = parser.parse_args(argv)

    source = Path(args.source).resolve()
    if not source.is_dir():
        print(f"[reconcile] ERROR: source no existe: {source}")
        return 1

    dest = canonical_checkout(source)
    motor_root = Path(__file__).resolve().parents[1]

    print(f"[reconcile] source (worktree)  : {source}")
    print(f"[reconcile] dest   (CANONICO)  : {dest}")

    if source == dest:
        print("[reconcile] source YA es el checkout canonico: nada que reconciliar")
        return 0

    src_obs, dst_obs = source / OBS_REL, dest / OBS_REL

    # Fail-closed: no escribir sobre una memoria que ya esta corrupta.
    rc = validate_strict(motor_root, dest)
    if rc != 0:
        print(f"[reconcile] ERROR: el destino NO valida --strict (returncode={rc})")
        print("[reconcile] no se escribe sobre una memoria invalida (fail-closed)")
        return 1
    print("[reconcile] destino valida --strict antes de escribir (returncode=0)")

    src, dst = load_records(src_obs), load_records(dst_obs)
    dst_keys = {record_key(r) for r in dst}

    lessons = [r for r in src if is_lesson(r)]
    skipped = len(src) - len(lessons)
    promote = [r for r in lessons if record_key(r) not in dst_keys]
    collisions = [r for r in lessons if record_key(r) in dst_keys]

    print(
        f"[reconcile] source: {len(src)} records "
        f"({len(lessons)} lecciones + {skipped} autogenerados EXCLUIDOS)"
    )
    print(f"[reconcile] dest  : {len(dst)} records")
    print(f"[reconcile] a promover: {len(promote)} | ya presentes: {len(collisions)}")

    for r in promote:
        print(
            f"[reconcile]   + [{r.get('domain')}] {r.get('topic')} "
            f"({r.get('source_ticket')})"
        )
    for r in collisions:
        print(f"[reconcile]   = ya existe, NO se sobrescribe: {record_key(r)}")

    if not args.apply:
        print("[reconcile] DRY-RUN: no se ha escrito nada (usa --apply)")
        return 0

    if not promote:
        print("[reconcile] nada que promover")
        return 0

    with dst_obs.open("a", encoding="utf-8", newline="\n") as fh:
        for r in promote:
            fh.write(json.dumps(r, ensure_ascii=True) + "\n")

    rc = validate_strict(motor_root, dest)
    print(f"[reconcile] destino valida --strict tras escribir (returncode={rc})")
    if rc != 0:
        print("[reconcile] ERROR: la escritura dejo la memoria invalida")
        return 1

    print(
        f"[reconcile] OK: {len(promote)} lecciones promovidas "
        f"({len(dst)} -> {len(load_records(dst_obs))} records)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
