#!/usr/bin/env python3
"""
Reconciliador de memoria portable del motor entre worktrees (WOT-2026-022y/022z).

EL PROBLEMA
-----------
`.agent/runtime/memory/observations.jsonl` es contenido del ARBOL DE TRABAJO, no
metadatos de git, y esta GITIGNORED (.gitignore:104) en TODAS las worktrees. Por tanto
NO se comparte entre worktrees Y NINGUN PUSH LO MUEVE: cada worktree tiene su propio
fichero y ningun commit lo recoge. Escribir memoria portable ahi PARECE una promocion y
no lo es: la leccion nunca sale de la maquina. La perdida es silenciosa.

EL VEHICULO PORTABLE REAL: EL ARCHIVE TRACKEADO
-----------------------------------------------
Lo unico que viaja es `.agent/runtime/memory/archive/observations.YYYY-MM.jsonl`, que SI
esta versionado (`git ls-files .agent/runtime/memory/archive/`) y es lo que tocan los
commits de promocion reales del motor. Por eso este script promueve AL ARCHIVE del
checkout canonico, no al `observations.jsonl` runtime.

Convencion del archive: UN FICHERO POR MES, `observations.YYYY-MM.jsonl` (UTC). El mes en
curso se crea si no existe. Los ficheros de meses anteriores NO se tocan, pero SI se leen:
el dedup cruza contra TODOS los `archive/*.jsonl`, de modo que una leccion promovida en
junio no se re-promueve en julio.

Tras `--apply` hay que COMMITEAR el archive: la promocion no existe hasta que esta en un
commit (y `scripts/check_portable_memory_promotion.py` es la barrera que lo detecta).

CORRECCION (022z): la version original de este script (022y) escribia en
`observations.jsonl` -- el fichero gitignored. Diagnosticaba bien el problema en su propio
docstring y luego escribia en el fichero que no viaja: "reconciliaba" entre worktrees algo
que ningun push mueve.

QUE RECONCILIA (y que NO)
-------------------------
Solo se promueven las observaciones ESCRITAS A MANO. Los topics de la lista
AUTOGENERATED_TOPICS los emite `scripts/session_close_observations.py` en CADA cierre
de sesion (telemetria mecanica: "Ticket X completado: ...", "Decisiones
arquitectonicas documentadas en X"). El checkout canonico ya acumula los suyos, asi
que copiarlos desde otra worktree solo ensuciaria la memoria con ruido -- e incluso
con registros vacios ("completado: Unknown"). Se EXCLUYEN por diseno.

IDENTIDAD DEL RECORD
--------------------
La clave es `(topic, source_ticket)`, NUNCA `topic` a secas: `topic` es una etiqueta
generica reutilizada (p.ej. "architecture" tiene decenas de records, uno por ticket).
Deduplicar por `topic` descartaria records legitimos como si fueran duplicados.

Una clave que ya existe en el destino NO se sobrescribe: se reporta como colision para
decision humana (nunca un merge a ciegas).

Uso:
    python scripts/reconcile_portable_memory.py --source <worktree> [--apply]

Sin `--apply` es un DRY-RUN (read-only): enumera lo que promoveria y no escribe nada.

Salida:
- Exit 0: reconciliacion correcta (o dry-run limpio).
- Exit 1: el destino no es el checkout canonico, o `validate_observations --strict`
  falla antes/despues de escribir (fail-closed: no se deja memoria invalida).
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# WOT-2026-024r (A1): la convencion del archive (mes-a-mes UTC, recorrer TODOS los
# meses, clave de dedup) vive UNA sola vez en `bus/portable_memory_archive.py`.
# Este script y `bus/memory_loader.py` la consumen. Duplicarla daria dos
# definiciones de identidad de observacion que divergirian en silencio.
from bus.portable_memory_archive import (
    ARCHIVE_DIR_REL,
    CorruptArchiveError,
    iter_archive_months,
    read_archive_observations,
    record_key,
)


# Fichero RUNTIME (gitignored): fuente de lecciones, NUNCA destino de promocion.
OBS_REL = Path(".agent/runtime/memory/observations.jsonl")

# Topics emitidos automaticamente por scripts/session_close_observations.py en cada
# cierre. NO son lecciones: son telemetria. El canonico ya genera los suyos.
AUTOGENERATED_TOPICS = frozenset({"architecture", "ticket-completion"})


def _git(repo: Path, *args: str) -> str:
    r = subprocess.run(  # noqa: S603
        ["git", *args],  # noqa: S607
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=False,
    )
    return r.stdout.strip()


class AmbiguousCanonicalCheckoutError(Exception):
    """Ninguna o mas de una worktree lleva la rama que publica memoria portable.

    Fail-closed deliberado (WOT-2026-025m): adivinar el destino en presencia de
    ambiguedad escribiria en el checkout equivocado en silencio (returncode 0
    y memoria perdida), exactamente el defecto que este ticket corrige.
    """


# Rama que publica la memoria portable. En esta topologia es siempre `main`:
# es la rama que se pushea y de la que vive el archive trackeado.
PUBLISHING_BRANCH = "main"


def canonical_checkout(repo: Path) -> Path:
    """La raiz del checkout que PUBLICA memoria portable: la worktree que
    tiene ``PUBLISHING_BRANCH`` (``main``) haciendo checkout, no la que
    resuelva ``--git-common-dir``.

    CORRECCION (WOT-2026-025m): la version anterior resolvia por
    ``--git-common-dir`` (el `.git` REAL compartido por todas las worktrees) y
    devolvia su directorio padre. Eso es robusto para localizar el `.git`
    compartido, pero NO identifica que worktree tiene `main` -- en una
    topologia con el checkout primario DETACHED y `main` en una worktree
    enlazada (p.ej. `_dev`), `--git-common-dir` sigue apuntando al primario, y
    el reconciliador promocionaba memoria a un checkout que nunca se pushea.

    Se enumera `git worktree list --porcelain` y se elige la worktree cuya
    linea `branch` es `refs/heads/<PUBLISHING_BRANCH>`. Fail-closed si no hay
    exactamente una coincidencia (ver `AmbiguousCanonicalCheckoutError`).
    """
    raw = _git(repo, "worktree", "list", "--porcelain")
    matches: list[Path] = []
    current_worktree: Path | None = None
    for line in raw.splitlines():
        if line.startswith("worktree "):
            current_worktree = Path(line[len("worktree ") :]).resolve()
        elif (
            line == f"branch refs/heads/{PUBLISHING_BRANCH}"
            and current_worktree is not None
        ):
            matches.append(current_worktree)

    if len(matches) == 1:
        return matches[0]

    # Un solo checkout (sin worktrees adicionales) sigue funcionando: si `repo`
    # mismo tiene `main`, ya esta en `matches` con longitud 1 y se devolvio
    # arriba. Si no hay NINGUNA coincidencia o hay MAS DE UNA, no se adivina.
    raise AmbiguousCanonicalCheckoutError(
        f"no se pudo determinar de forma UNAMBIGUA la worktree que publica "
        f"'{PUBLISHING_BRANCH}' (coincidencias: {len(matches)}). "
        f"git worktree list --porcelain:\n{raw}"
    )


def is_canonical(repo: Path) -> bool:
    toplevel = Path(_git(repo, "rev-parse", "--show-toplevel")).resolve()
    try:
        return toplevel == canonical_checkout(repo)
    except AmbiguousCanonicalCheckoutError:
        return False


#: Un fichero de memoria existe pero no es JSONL parseable.
#:
#: Se distingue de "no existe" (memoria vacia, legitima) y de "invalido segun el
#: schema" (lo caza `validate_observations --strict`). Un JSON roto ni siquiera llega
#: al validador: revienta al parsear. Sin esta excepcion el fallo salia como TRACEBACK
#: -- fail-closed de facto (returncode != 0) pero por CRASH, no por barrera: el
#: operador no sabia que fichero ni que linea, y "el script peto" es indistinguible de
#: un bug del propio script.
#:
#: WOT-2026-024r (A1): es el MISMO tipo que `CorruptArchiveError` del modulo
#: extraido, no una clase hermana. Si fueran distintas, `load_archive_records`
#: (ahora del modulo) lanzaria una excepcion que el `except CorruptMemoryError`
#: de `main()` NO capturaria, y una memoria corrupta volveria a salir como
#: traceback en vez de como barrera -- justo la regresion que este alias impide.
CorruptMemoryError = CorruptArchiveError


def load_records(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    records: list[dict] = []
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError as exc:
            raise CorruptMemoryError(f"{path}:{lineno}: JSON invalido ({exc})") from exc
    return records


def is_lesson(record: dict) -> bool:
    return record.get("topic") not in AUTOGENERATED_TOPICS


def current_archive_file(target_root: Path) -> Path:
    """El fichero de archive del MES EN CURSO (UTC) del destino.

    Convencion: `archive/observations.YYYY-MM.jsonl`, uno por mes. Si el mes actual aun
    no tiene fichero, se crea al escribir.
    """
    stamp = datetime.now(timezone.utc).strftime("%Y-%m")
    return target_root / ARCHIVE_DIR_REL / f"observations.{stamp}.jsonl"


# WOT-2026-024r (A1): `archive_files` y `load_archive_records` vivian aqui
# duplicando la convencion. Ahora son alias del modulo extraido -- mismo
# comportamiento, una sola definicion. `record_key` viene del mismo import.
archive_files = iter_archive_months
load_archive_records = read_archive_observations


def validate_strict(motor_root: Path, target_file: Path) -> int:
    """Devuelve el returncode REAL de `validate_observations.py --strict` sobre
    `target_file` (el fichero de ARCHIVE del destino que se va a escribir).

    `--file` es OBLIGATORIO aqui: el validador resuelve su fichero por defecto con
    `Path(__file__).parent.parent` (el repo DEL SCRIPT), ignorando el `cwd`. Lanzarlo
    sin `--file` validaria SIEMPRE la memoria del motor y devolveria 0 aunque la del
    destino estuviese corrupta: un falso-verde que anula la barrera fail-closed entera.

    Nunca leer `$?` tras un pipe: seria el exit del ultimo comando de la tuberia.

    Caso "el fichero aun no existe" (primer mes del archive): NO es memoria invalida, es
    memoria vacia -> returncode 0. Hay que cortocircuitarlo porque `validate_observations`
    trata la inexistencia como un "aviso" pero su `main()` devuelve 1 en cuanto la lista de
    avisos no esta vacia; delegar ahi convertiria un destino virgen en un fail-closed
    permanente que jamas dejaria crear el primer fichero del mes.
    """
    if not target_file.exists():
        return 0
    r = subprocess.run(  # noqa: S603
        [
            sys.executable,
            str(motor_root / "scripts" / "validate_observations.py"),
            "--strict",
            "--file",
            str(target_file),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    return r.returncode


def validate_dest_archive(motor_root: Path, dest: Path, dst_archive: Path) -> bool:
    """Fail-closed: TODO archive que alimenta el dedup debe validar `--strict`.

    Se validan TODOS los `archive/*.jsonl` del destino, no solo el fichero del mes en
    curso que se va a escribir. Validar unicamente el fichero ESCRITO dejaba un hueco:
    un archive de un mes ANTERIOR con un `domain` fuera del enum VALID_DOMAINS es
    sintacticamente parseable, asi que entraba en el set de dedup sin pasar jamas por
    `--strict`. Y el dedup DECIDE que se promueve: alimentarlo con memoria que la
    barrera nunca miro es confiar en datos no validados para tomar la decision.

    El fichero del mes en curso se incluye aunque aun no exista: `validate_strict`
    cortocircuita el caso "no existe" como memoria VACIA (valida), no como invalida --
    si no, el primer dia de cada mes seria un fail-closed permanente que impediria crear
    el primer archive.

    Devuelve True si todo valida; False (y ya ha impreso el motivo) si algo falla.
    """
    for target in sorted({*archive_files(dest), dst_archive}):
        rc = validate_strict(motor_root, target)
        if rc != 0:
            print(f"[reconcile] ERROR: {target} NO valida --strict (returncode={rc})")
            print("[reconcile] no se escribe sobre una memoria invalida (fail-closed)")
            return False
    print("[reconcile] el archive del destino valida --strict (returncode=0)")
    return True


def main(argv: list[str] | None = None) -> int:
    """Entrypoint: traduce una memoria corrupta en un ERROR, no en un traceback.

    `CorruptMemoryError` ya era fail-closed de facto (la excepcion aborta y no se
    escribe nada), pero salia como traceback: el returncode != 0 llegaba por CRASH y no
    por barrera, y el operador no veia ni el fichero ni la linea. "El script peto" es
    indistinguible de un bug del propio script.
    """
    try:
        return _run(argv)
    except CorruptMemoryError as exc:
        print(f"[reconcile] ERROR: memoria corrupta: {exc}")
        print("[reconcile] no se escribe sobre una memoria ilegible (fail-closed)")
        return 1
    except AmbiguousCanonicalCheckoutError as exc:
        print(f"[reconcile] ERROR: destino ambiguo: {exc}")
        print("[reconcile] no se adivina el checkout canonico (fail-closed)")
        return 1


def _promote_one(
    *,
    motor_root: Path,
    source: Path,
    dest: Path,
    obs_id: str,
    apply: bool,
) -> int:
    """VIA CURADA: promueve UNA leccion por `id` (WOT-2026-026f / DEC-026F-001).

    Por que existe: la promocion automatica va POR ANTIGUEDAD (cutoff 30d de
    `memory_consolidate.split_by_age`), y el reconciliador solo mueve memoria
    ENTRE worktrees. En un checkout CANONICO (`source == dest`) no habia ninguna
    via: una leccion valiosa de hoy quedaba huerfana hasta cruzar el umbral, y el
    promotion-guard recomendaba precisamente el comando que ahi es NO-OP -- la
    trampa del "exit 0 = no hice nada" dentro de la barrera que existe para
    evitarla. DEC-026F-001 (B1) formaliza esta via SIN quitar la automatica.

    Es ADITIVA y explicita: exige `--promote-id` + `--apply` (confirmacion), y
    reutiliza la MISMA barrera fail-closed que la via automatica
    (`validate_dest_archive` antes, `validate_strict` despues). No es un bypass.

    Before: `source` legible; `obs_id` es el campo `id` de un record de
        `observations.jsonl` del source.
    During: localiza el record por `id` (fail-closed si no existe o si hay
        ambiguedad), deduplica contra TODOS los archive/*.jsonl del destino
        (por `id` y por `record_key`), valida `--strict` ANTES de escribir y
        vuelve a validar DESPUES.
    After: 0 si promovio (o si ya estaba / dry-run); != 0 si el id no existe, si
        el archive no valida, o si la escritura dejo memoria invalida.
    """
    src_obs = source / OBS_REL
    dst_archive = current_archive_file(dest)
    print(f"[reconcile] VIA CURADA (--promote-id {obs_id})")
    print(f"[reconcile] destino (ARCHIVE TRACKEADO): {dst_archive}")

    src = load_records(src_obs)
    matches = [r for r in src if r.get("id") == obs_id]
    if not matches:
        print(
            f"[reconcile] ERROR: no hay ninguna leccion con id={obs_id!r} en {src_obs}"
        )
        print("[reconcile] no se promueve lo que no existe (fail-closed)")
        return 1
    if len(matches) > 1:
        print(
            f"[reconcile] ERROR: id={obs_id!r} aparece {len(matches)} veces en el source"
        )
        print("[reconcile] no se adivina cual promover (fail-closed)")
        return 1
    record = matches[0]
    if not is_lesson(record):
        print(f"[reconcile] ERROR: id={obs_id!r} no es una LECCION (es autogenerado)")
        print("[reconcile] la via curada promueve lecciones, no telemetria")
        return 1

    if not validate_dest_archive(motor_root, dest, dst_archive):
        return 1

    dst = load_archive_records(dest)
    if any(r.get("id") == obs_id for r in dst) or record_key(record) in {
        record_key(r) for r in dst
    }:
        print(f"[reconcile] = ya en el archive, NO se sobrescribe: {obs_id}")
        return 0

    print(
        f"[reconcile]   + [{record.get('domain')}] {record.get('topic')} "
        f"({record.get('source_ticket')})"
    )
    if not apply:
        print("[reconcile] DRY-RUN: no se ha escrito nada (usa --apply)")
        return 0

    dst_archive.parent.mkdir(parents=True, exist_ok=True)
    with dst_archive.open("a", encoding="utf-8", newline="\n") as fh:
        fh.write(json.dumps(record, ensure_ascii=True) + "\n")

    rc = validate_strict(motor_root, dst_archive)
    print(f"[reconcile] destino valida --strict tras escribir (returncode={rc})")
    if rc != 0:
        print("[reconcile] ERROR: la escritura dejo la memoria invalida")
        return 1

    print(f"[reconcile] OK: leccion {obs_id} promovida al ARCHIVE")
    print(f"[reconcile] SIGUIENTE PASO: commitea {ARCHIVE_DIR_REL.as_posix()} -- sin")
    print("[reconcile] commit, la promocion no viaja.")
    return 0


def _build_parser() -> argparse.ArgumentParser:
    """CLI del reconciliador. Extraido de `_run` para que la rama de la via
    curada (WOT-2026-026f) no empuje la complejidad de `_run` sobre el limite."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument(
        "--source", required=True, help="worktree cuya memoria se reconcilia"
    )
    parser.add_argument(
        "--apply", action="store_true", help="escribir (por defecto: dry-run)"
    )
    parser.add_argument(
        "--promote-id",
        metavar="ID",
        help=(
            "VIA CURADA (WOT-2026-026f / DEC-026F-001): promueve UNA leccion "
            "concreta por su campo `id` al archive trackeado, tambien cuando el "
            "source ES el checkout canonico. Requiere --apply para escribir."
        ),
    )
    return parser


def _run(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    source = Path(args.source).resolve()
    if not source.is_dir():
        print(f"[reconcile] ERROR: source no existe: {source}")
        return 1

    dest = canonical_checkout(source)
    motor_root = Path(__file__).resolve().parents[1]

    print(f"[reconcile] source (worktree)  : {source}")
    print(f"[reconcile] dest   (CANONICO)  : {dest}")

    if args.promote_id:
        return _promote_one(
            motor_root=motor_root,
            source=source,
            dest=dest,
            obs_id=args.promote_id,
            apply=args.apply,
        )

    if source == dest:
        print("[reconcile] source YA es el checkout canonico: nada que reconciliar")
        print(
            "[reconcile] (para promover UNA leccion concreta YA, usa la via curada: "
            "--promote-id <id> --apply)"
        )
        return 0

    return _reconcile_all(
        motor_root=motor_root, source=source, dest=dest, apply=args.apply
    )


def _reconcile_all(*, motor_root: Path, source: Path, dest: Path, apply: bool) -> int:
    """Via AUTOMATICA (historica): promueve TODAS las lecciones nuevas de un
    worktree NO canonico al archive del canonico.

    Extraida de `_run` al anadir la via curada (WOT-2026-026f): `_run` queda como
    despachador entre las dos rutas simetricas y ninguna de las dos carga con la
    complejidad de la otra.
    """
    src_obs = source / OBS_REL
    dst_archive = current_archive_file(dest)

    print(f"[reconcile] destino (ARCHIVE TRACKEADO): {dst_archive}")

    if not validate_dest_archive(motor_root, dest, dst_archive):
        return 1

    src = load_records(src_obs)
    # El dedup cruza contra TODOS los archive/*.jsonl del destino, no solo el del mes
    # en curso: lo promovido en un mes anterior YA viajo.
    dst = load_archive_records(dest)
    dst_keys = {record_key(r) for r in dst}

    lessons = [r for r in src if is_lesson(r)]
    skipped = len(src) - len(lessons)
    promote = [r for r in lessons if record_key(r) not in dst_keys]
    collisions = [r for r in lessons if record_key(r) in dst_keys]

    print(
        f"[reconcile] source: {len(src)} records "
        f"({len(lessons)} lecciones + {skipped} autogenerados EXCLUIDOS)"
    )
    print(
        f"[reconcile] dest  : {len(dst)} records en "
        f"{len(archive_files(dest))} fichero(s) de archive"
    )
    print(f"[reconcile] a promover: {len(promote)} | ya presentes: {len(collisions)}")

    for r in promote:
        print(
            f"[reconcile]   + [{r.get('domain')}] {r.get('topic')} "
            f"({r.get('source_ticket')})"
        )
    for r in collisions:
        print(f"[reconcile]   = ya en el archive, NO se sobrescribe: {record_key(r)}")

    if not apply:
        print("[reconcile] DRY-RUN: no se ha escrito nada (usa --apply)")
        return 0

    if not promote:
        print("[reconcile] nada que promover")
        return 0

    dst_archive.parent.mkdir(parents=True, exist_ok=True)
    with dst_archive.open("a", encoding="utf-8", newline="\n") as fh:
        for r in promote:
            fh.write(json.dumps(r, ensure_ascii=True) + "\n")

    rc = validate_strict(motor_root, dst_archive)
    print(f"[reconcile] destino valida --strict tras escribir (returncode={rc})")
    if rc != 0:
        print("[reconcile] ERROR: la escritura dejo la memoria invalida")
        return 1

    print(
        f"[reconcile] OK: {len(promote)} lecciones promovidas al ARCHIVE "
        f"({len(dst)} -> {len(load_archive_records(dest))} records)"
    )
    print(f"[reconcile] SIGUIENTE PASO: commitea {ARCHIVE_DIR_REL.as_posix()} en el")
    print("[reconcile] canonico -- sin commit, la promocion no viaja.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
