#!/usr/bin/env python3
"""
Reconciliador de memoria portable del motor entre worktrees (WOT-2026-022y/022z).

EL PROBLEMA
-----------
`.agent/runtime/memory/observations.jsonl` es contenido del ARBOL DE TRABAJO, no
metadatos de git, y esta GITIGNORED (.gitignore:104) en TODAS las worktrees. Por tanto
NO se comparte entre worktrees Y NINGUN PUSH LO MUEVE: cada worktree tiene su propio
fichero y ningun commit lo recoge. Escribir memoria portable ahi PARECE una promocion y
no lo es: la leccion nunca sale de la maquina. La perdida es silenciosa.

EL VEHICULO PORTABLE REAL: EL ARCHIVE TRACKEADO
-----------------------------------------------
Lo unico que viaja es `.agent/runtime/memory/archive/observations.YYYY-MM.jsonl`, que SI
esta versionado (`git ls-files .agent/runtime/memory/archive/`) y es lo que tocan los
commits de promocion reales del motor. Por eso este script promueve AL ARCHIVE del
checkout canonico, no al `observations.jsonl` runtime.

Convencion del archive: UN FICHERO POR MES, `observations.YYYY-MM.jsonl` (UTC). El mes en
curso se crea si no existe. Los ficheros de meses anteriores NO se tocan, pero SI se leen:
el dedup cruza contra TODOS los `archive/*.jsonl`, de modo que una leccion promovida en
junio no se re-promueve en julio.

Tras `--apply` hay que COMMITEAR el archive: la promocion no existe hasta que esta en un
commit (y `scripts/check_portable_memory_promotion.py` es la barrera que lo detecta).

CORRECCION (022z): la version original de este script (022y) escribia en
`observations.jsonl` -- el fichero gitignored. Diagnosticaba bien el problema en su propio
docstring y luego escribia en el fichero que no viaja: "reconciliaba" entre worktrees algo
que ningun push mueve.

QUE RECONCILIA (y que NO)
-------------------------
Solo se promueven las observaciones ESCRITAS A MANO. Los topics de la lista
AUTOGENERATED_TOPICS los emite `scripts/session_close_observations.py` en CADA cierre
de sesion (telemetria mecanica: "Ticket X completado: ...", "Decisiones
arquitectonicas documentadas en X"). El checkout canonico ya acumula los suyos, asi
que copiarlos desde otra worktree solo ensuciaria la memoria con ruido -- e incluso
con registros vacios ("completado: Unknown"). Se EXCLUYEN por diseno.

IDENTIDAD DEL RECORD
--------------------
La clave es `(topic, source_ticket)`, NUNCA `topic` a secas: `topic` es una etiqueta
generica reutilizada (p.ej. "architecture" tiene decenas de records, uno por ticket).
Deduplicar por `topic` descartaria records legitimos como si fueran duplicados.

Una clave que ya existe en el destino NO se sobrescribe: se reporta como colision para
decision humana (nunca un merge a ciegas).

Uso:
    python scripts/reconcile_portable_memory.py --source <worktree> [--apply]

Sin `--apply` es un DRY-RUN (read-only): enumera lo que promoveria y no escribe nada.

Salida:
- Exit 0: reconciliacion correcta (o dry-run limpio).
- Exit 1: el destino no es el checkout canonico, o `validate_observations --strict`
  falla antes/despues de escribir (fail-closed: no se deja memoria invalida).
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


# Fichero RUNTIME (gitignored): fuente de lecciones, NUNCA destino de promocion.
OBS_REL = Path(".agent/runtime/memory/observations.jsonl")

# Directorio ARCHIVE (TRACKEADO en git): el unico vehiculo portable real.
ARCHIVE_DIR_REL = Path(".agent/runtime/memory/archive")

# Topics emitidos automaticamente por scripts/session_close_observations.py en cada
# cierre. NO son lecciones: son telemetria. El canonico ya genera los suyos.
AUTOGENERATED_TOPICS = frozenset({"architecture", "ticket-completion"})


def _git(repo: Path, *args: str) -> str:
    r = subprocess.run(  # noqa: S603
        ["git", *args],  # noqa: S607
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=False,
    )
    return r.stdout.strip()


def canonical_checkout(repo: Path) -> Path:
    """La raiz del checkout CANONICO del repo que contiene `repo`.

    Se resuelve por `--git-common-dir` (el `.git` REAL, compartido por todas las
    worktrees): su directorio padre es el checkout canonico. Es robusto, a diferencia
    de heuristicas sobre la cadena del `--git-dir` (buscar "worktrees/" en el path
    funciona por accidente de nombres, no por construccion).
    """
    raw = Path(_git(repo, "rev-parse", "--git-common-dir"))
    # `--git-common-dir` puede venir RELATIVO (p.ej. ".git" en el propio canonico).
    # Un `.resolve()` directo lo resolveria contra el CWD DEL PROCESO, no contra el
    # repo -> raiz equivocada. Hay que anclarlo al repo.
    common = raw if raw.is_absolute() else (repo / raw)
    return common.resolve().parent


def is_canonical(repo: Path) -> bool:
    toplevel = Path(_git(repo, "rev-parse", "--show-toplevel")).resolve()
    return toplevel == canonical_checkout(repo)


class CorruptMemoryError(Exception):
    """Un fichero de memoria existe pero no es JSONL parseable.

    Se distingue de "no existe" (memoria vacia, legitima) y de "invalido segun el
    schema" (lo caza `validate_observations --strict`). Un JSON roto ni siquiera llega
    al validador: revienta al parsear. Sin esta excepcion el fallo salia como TRACEBACK
    -- fail-closed de facto (returncode != 0) pero por CRASH, no por barrera: el
    operador no sabia que fichero ni que linea, y "el script peto" es indistinguible de
    un bug del propio script.
    """


def load_records(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    records: list[dict] = []
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError as exc:
            raise CorruptMemoryError(f"{path}:{lineno}: JSON invalido ({exc})") from exc
    return records


def record_key(record: dict) -> tuple[str, str | None]:
    return (record.get("topic", ""), record.get("source_ticket"))


def is_lesson(record: dict) -> bool:
    return record.get("topic") not in AUTOGENERATED_TOPICS


def current_archive_file(target_root: Path) -> Path:
    """El fichero de archive del MES EN CURSO (UTC) del destino.

    Convencion: `archive/observations.YYYY-MM.jsonl`, uno por mes. Si el mes actual aun
    no tiene fichero, se crea al escribir.
    """
    stamp = datetime.now(timezone.utc).strftime("%Y-%m")
    return target_root / ARCHIVE_DIR_REL / f"observations.{stamp}.jsonl"


def archive_files(target_root: Path) -> list[Path]:
    """TODOS los ficheros de archive del destino, no solo el del mes en curso.

    El dedup DEBE cruzar contra todos: una leccion promovida en un mes anterior ya
    viajo, y re-promoverla en el mes en curso la duplicaria en la memoria portable.
    """
    archive_dir = target_root / ARCHIVE_DIR_REL
    if not archive_dir.is_dir():
        return []
    return sorted(archive_dir.glob("observations.*.jsonl"))


def load_archive_records(target_root: Path) -> list[dict]:
    records: list[dict] = []
    for path in archive_files(target_root):
        records.extend(load_records(path))
    return records


def validate_strict(motor_root: Path, target_file: Path) -> int:
    """Devuelve el returncode REAL de `validate_observations.py --strict` sobre
    `target_file` (el fichero de ARCHIVE del destino que se va a escribir).

    `--file` es OBLIGATORIO aqui: el validador resuelve su fichero por defecto con
    `Path(__file__).parent.parent` (el repo DEL SCRIPT), ignorando el `cwd`. Lanzarlo
    sin `--file` validaria SIEMPRE la memoria del motor y devolveria 0 aunque la del
    destino estuviese corrupta: un falso-verde que anula la barrera fail-closed entera.

    Nunca leer `$?` tras un pipe: seria el exit del ultimo comando de la tuberia.

    Caso "el fichero aun no existe" (primer mes del archive): NO es memoria invalida, es
    memoria vacia -> returncode 0. Hay que cortocircuitarlo porque `validate_observations`
    trata la inexistencia como un "aviso" pero su `main()` devuelve 1 en cuanto la lista de
    avisos no esta vacia; delegar ahi convertiria un destino virgen en un fail-closed
    permanente que jamas dejaria crear el primer fichero del mes.
    """
    if not target_file.exists():
        return 0
    r = subprocess.run(  # noqa: S603
        [
            sys.executable,
            str(motor_root / "scripts" / "validate_observations.py"),
            "--strict",
            "--file",
            str(target_file),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    return r.returncode


def validate_dest_archive(motor_root: Path, dest: Path, dst_archive: Path) -> bool:
    """Fail-closed: TODO archive que alimenta el dedup debe validar `--strict`.

    Se validan TODOS los `archive/*.jsonl` del destino, no solo el fichero del mes en
    curso que se va a escribir. Validar unicamente el fichero ESCRITO dejaba un hueco:
    un archive de un mes ANTERIOR con un `domain` fuera del enum VALID_DOMAINS es
    sintacticamente parseable, asi que entraba en el set de dedup sin pasar jamas por
    `--strict`. Y el dedup DECIDE que se promueve: alimentarlo con memoria que la
    barrera nunca miro es confiar en datos no validados para tomar la decision.

    El fichero del mes en curso se incluye aunque aun no exista: `validate_strict`
    cortocircuita el caso "no existe" como memoria VACIA (valida), no como invalida --
    si no, el primer dia de cada mes seria un fail-closed permanente que impediria crear
    el primer archive.

    Devuelve True si todo valida; False (y ya ha impreso el motivo) si algo falla.
    """
    for target in sorted({*archive_files(dest), dst_archive}):
        rc = validate_strict(motor_root, target)
        if rc != 0:
            print(f"[reconcile] ERROR: {target} NO valida --strict (returncode={rc})")
            print("[reconcile] no se escribe sobre una memoria invalida (fail-closed)")
            return False
    print("[reconcile] el archive del destino valida --strict (returncode=0)")
    return True


def main(argv: list[str] | None = None) -> int:
    """Entrypoint: traduce una memoria corrupta en un ERROR, no en un traceback.

    `CorruptMemoryError` ya era fail-closed de facto (la excepcion aborta y no se
    escribe nada), pero salia como traceback: el returncode != 0 llegaba por CRASH y no
    por barrera, y el operador no veia ni el fichero ni la linea. "El script peto" es
    indistinguible de un bug del propio script.
    """
    try:
        return _run(argv)
    except CorruptMemoryError as exc:
        print(f"[reconcile] ERROR: memoria corrupta: {exc}")
        print("[reconcile] no se escribe sobre una memoria ilegible (fail-closed)")
        return 1


def _run(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument(
        "--source", required=True, help="worktree cuya memoria se reconcilia"
    )
    parser.add_argument(
        "--apply", action="store_true", help="escribir (por defecto: dry-run)"
    )
    args = parser.parse_args(argv)

    source = Path(args.source).resolve()
    if not source.is_dir():
        print(f"[reconcile] ERROR: source no existe: {source}")
        return 1

    dest = canonical_checkout(source)
    motor_root = Path(__file__).resolve().parents[1]

    print(f"[reconcile] source (worktree)  : {source}")
    print(f"[reconcile] dest   (CANONICO)  : {dest}")

    if source == dest:
        print("[reconcile] source YA es el checkout canonico: nada que reconciliar")
        return 0

    src_obs = source / OBS_REL
    dst_archive = current_archive_file(dest)

    print(f"[reconcile] destino (ARCHIVE TRACKEADO): {dst_archive}")

    if not validate_dest_archive(motor_root, dest, dst_archive):
        return 1

    src = load_records(src_obs)
    # El dedup cruza contra TODOS los archive/*.jsonl del destino, no solo el del mes
    # en curso: lo promovido en un mes anterior YA viajo.
    dst = load_archive_records(dest)
    dst_keys = {record_key(r) for r in dst}

    lessons = [r for r in src if is_lesson(r)]
    skipped = len(src) - len(lessons)
    promote = [r for r in lessons if record_key(r) not in dst_keys]
    collisions = [r for r in lessons if record_key(r) in dst_keys]

    print(
        f"[reconcile] source: {len(src)} records "
        f"({len(lessons)} lecciones + {skipped} autogenerados EXCLUIDOS)"
    )
    print(
        f"[reconcile] dest  : {len(dst)} records en "
        f"{len(archive_files(dest))} fichero(s) de archive"
    )
    print(f"[reconcile] a promover: {len(promote)} | ya presentes: {len(collisions)}")

    for r in promote:
        print(
            f"[reconcile]   + [{r.get('domain')}] {r.get('topic')} "
            f"({r.get('source_ticket')})"
        )
    for r in collisions:
        print(f"[reconcile]   = ya en el archive, NO se sobrescribe: {record_key(r)}")

    if not args.apply:
        print("[reconcile] DRY-RUN: no se ha escrito nada (usa --apply)")
        return 0

    if not promote:
        print("[reconcile] nada que promover")
        return 0

    dst_archive.parent.mkdir(parents=True, exist_ok=True)
    with dst_archive.open("a", encoding="utf-8", newline="\n") as fh:
        for r in promote:
            fh.write(json.dumps(r, ensure_ascii=True) + "\n")

    rc = validate_strict(motor_root, dst_archive)
    print(f"[reconcile] destino valida --strict tras escribir (returncode={rc})")
    if rc != 0:
        print("[reconcile] ERROR: la escritura dejo la memoria invalida")
        return 1

    print(
        f"[reconcile] OK: {len(promote)} lecciones promovidas al ARCHIVE "
        f"({len(dst)} -> {len(load_archive_records(dest))} records)"
    )
    print(f"[reconcile] SIGUIENTE PASO: commitea {ARCHIVE_DIR_REL.as_posix()} en el")
    print("[reconcile] canonico -- sin commit, la promocion no viaja.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
