"""Contract tests for scripts/check_portable_memory_promotion.py (WOT-2026-022z).

The guard detects ORPHANED LESSONS: a hand-written observation that lives only in
`.agent/runtime/memory/observations.jsonl` (GITIGNORED in every worktree, so no push
moves it) and is absent from the tracked archive
`.agent/runtime/memory/archive/observations.YYYY-MM.jsonl` -- the only file that
actually travels. The session believes it promoted the lesson; it never leaves the box.

Load-bearing properties:

1. The verdict is decided by TWO conditions ANDed: "is a lesson" AND "not in the
   archive". Test (f) isolates the branch: autogenerated telemetry absent from the
   archive is NOT an orphan (it is not meant to travel) -> exit 0.
   Mutation: neutralize the archive comparison (treat the archive set as containing
   everything) -> the orphan test goes RED.

2. Exit codes are DIFFERENTIATED: 0 = clean, 1 = the TOOL failed, 4 = there ARE
   orphans. Collapsing 4 into 1 (or into 0) makes the guard useless as an automated
   barrier: "there are orphans" is a FINDING, not a broken tool.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


SCRIPT = (
    Path(__file__).resolve().parents[2]
    / "scripts"
    / "check_portable_memory_promotion.py"
)
OBS_REL = Path(".agent/runtime/memory/observations.jsonl")
ARCHIVE_DIR_REL = Path(".agent/runtime/memory/archive")

EXIT_OK = 0
EXIT_TOOL_ERROR = 1
EXIT_ORPHANS = 4


def _archive_rel(month: str | None = None) -> Path:
    stamp = month or datetime.now(timezone.utc).strftime("%Y-%m")
    return ARCHIVE_DIR_REL / f"observations.{stamp}.jsonl"


def _obs(topic: str, ticket: str, domain: str = "review-quality") -> dict:
    return {
        "timestamp": "2026-07-12T10:00:00Z",
        "topic": topic,
        "signal": f"senal de {topic} para {ticket}",
        "source": ticket,
        "source_ticket": ticket,
        "applies_to": "all",
        "confidence": 0.9,
        "domain": domain,
    }


def _write(path: Path, records: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(json.dumps(r) + "\n" for r in records), encoding="utf-8", newline="\n"
    )


def _make_repo(tmp_path: Path) -> Path:
    """A real git repo (the guard refuses to audit a non-repo: exit 1)."""
    repo = tmp_path / "repo"
    repo.mkdir()

    def run(*a: str) -> None:
        subprocess.run(
            ["git", *a], cwd=str(repo), capture_output=True, text=True, check=True
        )

    run("init", "-b", "main")
    run("config", "user.email", "t@t.t")
    run("config", "user.name", "t")
    (repo / "README").write_text("x", encoding="utf-8")
    run("add", "-A")
    run("commit", "-m", "base")
    return repo


def _run(repo: Path) -> subprocess.CompletedProcess:
    # returncode read directly -- never `$?` after a pipe.
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--project-root", str(repo)],
        capture_output=True,
        text=True,
        check=False,
    )


def test_lesson_absent_from_archive_is_an_orphan_and_is_named(tmp_path: Path) -> None:
    """(d) THE GUARD'S TEST: a lesson only in the gitignored runtime file is an
    orphan -> exit 4, and the output NAMES it (a mute count is not actionable).

    Mutation: neutralize the archive comparison -> RED.
    """
    repo = _make_repo(tmp_path)
    _write(repo / OBS_REL, [_obs("leccion-huerfana", "WOT-2026-111a")])
    _write(repo / _archive_rel(), [])

    r = _run(repo)

    assert r.returncode == EXIT_ORPHANS, (
        "a lesson present in the gitignored observations.jsonl and ABSENT from the "
        f"tracked archive must be reported as an orphan (exit 4); got {r.returncode}. "
        f"stdout: {r.stdout} stderr: {r.stderr}"
    )
    assert "leccion-huerfana" in r.stdout, "the guard must NAME each orphan"
    assert "WOT-2026-111a" in r.stdout, "the guard must report the source_ticket"
    # WOT-2026-038j: `_make_repo` builds a STANDALONE repo -- it is its own canonical
    # checkout (is_canonical == True), so a BARE reconciler call is a no-op here. The
    # remedy printed must be an APPLICABLE one, never the "exit 0 = did nothing" trap.
    # WOT-2026-026f narrows the ban: `--promote-id` IS applicable in a canonical
    # checkout (it is the curated route), so only the bare invocation stays forbidden.
    assert "memory_consolidate" in r.stdout, (
        "in a canonical checkout the automatic promotion vehicle is memory_consolidate "
        f"by age. stdout: {r.stdout}"
    )
    bare_reconciler = [
        line
        for line in r.stdout.splitlines()
        if "reconcile_portable_memory.py" in line and "--promote-id" not in line
    ]
    assert not bare_reconciler, (
        "a BARE reconciler remedy is a NO-OP in a canonical checkout (source==dest); "
        f"printing it is the very trap this guard exists to prevent: {bare_reconciler}"
    )


def test_orphan_in_canonical_checkout_names_the_applicable_remedy(
    tmp_path: Path,
) -> None:
    """(038j) A standalone repo (an independent repo_destino) IS its own canonical
    checkout: `reconcile_portable_memory --source <it>` returns 'nada que reconciliar'
    (source==dest) and writes nothing -- exit 0. A guard that fires exit 4 and then
    hands the operator that no-op command is the 'exit 0 = I did nothing' trap living
    INSIDE the barrier meant to prevent it. The applicable vehicle here is
    memory_consolidate archiving by age.

    Mutation: keep the old unconditional reconciler remedy -> RED (memory_consolidate
    absent, reconciler present).
    """
    repo = _make_repo(tmp_path)
    _write(repo / OBS_REL, [_obs("leccion-en-canonico", "WOT-2026-777a")])
    _write(repo / _archive_rel(), [])

    r = _run(repo)

    assert r.returncode == EXIT_ORPHANS, r.stdout + r.stderr
    assert "memory_consolidate" in r.stdout, (
        "a canonical checkout must be told the APPLICABLE remedy (memory_consolidate "
        f"by age); got: {r.stdout}"
    )
    # WOT-2026-026f: the invariant is "no NO-OP remedy", and the proxy for it had to
    # change. Until 026f, ANY `reconcile --source` here was a no-op, so banning the
    # substring was a faithful proxy. Now `--promote-id` makes the reconciler a REAL
    # route in a canonical checkout (DEC-026F-001), so the ban narrows to the BARE
    # invocation -- the one that still exits 0 without writing.
    bare_reconciler = [
        line
        for line in r.stdout.splitlines()
        if "reconcile_portable_memory.py" in line and "--promote-id" not in line
    ]
    assert not bare_reconciler, (
        "a BARE `reconcile --source ... --apply` is still a no-op in a canonical "
        f"checkout; the guard must not point at it. got: {bare_reconciler}"
    )
    assert "--promote-id" in r.stdout, (
        "the canonical branch must offer the curated route (WOT-2026-026f / D2); "
        f"got: {r.stdout}"
    )


def test_orphan_in_noncanonical_worktree_points_at_the_reconciler(
    tmp_path: Path,
) -> None:
    """(038j) The reconciler is NOT a no-op everywhere: in a LINKED worktree
    (is_canonical == False) it genuinely moves the lesson to the canonical archive.
    There the guard must keep pointing at it -- the fix branches the remedy, it does
    not delete a valid one.

    Mutation: make the remedy unconditional-memory_consolidate -> RED (reconciler
    absent in the branch where it IS the right answer).
    """
    canonical = _make_repo(tmp_path)
    linked = tmp_path / "linked_worktree"
    subprocess.run(
        ["git", "worktree", "add", str(linked)],
        cwd=str(canonical),
        capture_output=True,
        text=True,
        check=True,
    )
    _write(linked / OBS_REL, [_obs("leccion-en-worktree", "WOT-2026-888b")])
    _write(linked / _archive_rel(), [])

    r = _run(linked)

    assert r.returncode == EXIT_ORPHANS, r.stdout + r.stderr
    assert "reconcile_portable_memory.py" in r.stdout, (
        "a non-canonical worktree CAN be reconciled to its canonical checkout; the "
        f"guard must point at the reconciler here. got: {r.stdout}"
    )


def test_lesson_present_in_archive_is_clean(tmp_path: Path) -> None:
    """(e) The same lesson, already in the tracked archive -> exit 0."""
    repo = _make_repo(tmp_path)
    lesson = _obs("leccion-promovida", "WOT-2026-222b")
    _write(repo / OBS_REL, [lesson])
    _write(repo / _archive_rel(), [lesson])

    r = _run(repo)
    assert r.returncode == EXIT_OK, (
        f"a lesson already in the archive has travelled; got {r.returncode}. "
        f"stdout: {r.stdout}"
    )


def test_lesson_archived_in_another_month_is_clean(tmp_path: Path) -> None:
    """The archive set is built from ALL months, not just the current one: a lesson
    promoted in a previous month already travelled."""
    repo = _make_repo(tmp_path)
    lesson = _obs("leccion-de-otro-mes", "WOT-2026-333c")
    _write(repo / OBS_REL, [lesson])
    _write(repo / _archive_rel("2020-01"), [lesson])

    r = _run(repo)
    assert r.returncode == EXIT_OK, r.stdout + r.stderr


def test_autogenerated_telemetry_absent_from_archive_is_not_an_orphan(
    tmp_path: Path,
) -> None:
    """(f) BRANCH ISOLATION (021u lesson): the verdict needs BOTH conditions.

    Telemetry (`architecture` / `ticket-completion`, emitted by
    session_close_observations.py on every close) is NOT a portable lesson: it is not
    meant to travel, so its absence from the archive is NOT a finding. If the guard
    only checked "absent from the archive", this would be a false positive -- and the
    guard would fire on every single session.
    """
    repo = _make_repo(tmp_path)
    _write(
        repo / OBS_REL,
        [
            _obs("architecture", "WOT-2026-444d"),
            _obs("ticket-completion", "WOT-2026-444d"),
        ],
    )
    _write(repo / _archive_rel(), [])

    r = _run(repo)
    assert r.returncode == EXIT_OK, (
        "autogenerated telemetry absent from the archive is NOT an orphan; the "
        f"verdict requires 'is a lesson' AND 'not archived'. got {r.returncode}. "
        f"stdout: {r.stdout}"
    )


def test_non_repo_root_is_a_tool_error_not_a_finding(tmp_path: Path) -> None:
    """Exit 1 (tool failure) must NOT be confused with exit 4 (there are orphans).

    REFUTED PREMISE (found while writing this test): `tmp_path` lives INSIDE the motor
    tree (tests/sandbox/test_runtime/...), so a plain directory there still answers
    `git rev-parse --git-dir` with the MOTOR's .git. "Being inside a git repo" is not
    enough: the guard requires --project-root to BE the toplevel, otherwise it would
    happily audit a non-repo path and call it clean.
    """
    not_a_repo = tmp_path / "plain"
    (not_a_repo / OBS_REL).parent.mkdir(parents=True)
    _write(not_a_repo / OBS_REL, [_obs("x", "WOT-2026-555e")])

    r = _run(not_a_repo)
    assert r.returncode == EXIT_TOOL_ERROR, (
        f"a path that is not a git checkout root is a TOOL failure (exit 1), not a "
        f"finding; got {r.returncode}"
    )


def test_corrupt_jsonl_is_a_tool_error(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    obs = repo / OBS_REL
    obs.parent.mkdir(parents=True, exist_ok=True)
    obs.write_bytes(b"{not json\n")

    r = _run(repo)
    assert r.returncode == EXIT_TOOL_ERROR, (
        f"an unreadable memory file is a TOOL failure (exit 1); got {r.returncode}"
    )


def test_no_runtime_memory_is_clean(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    r = _run(repo)
    assert r.returncode == EXIT_OK, r.stdout + r.stderr


def test_same_topic_different_source_ticket_is_still_an_orphan(tmp_path: Path) -> None:
    """WOT-2026-023g: record_key is (topic, source_ticket), NEVER topic alone.

    Two lessons share a topic but differ in source_ticket; one is already in
    the archive, the other is only in the gitignored runtime. The guard must
    STILL flag the un-archived one -- the archived twin does NOT cover it,
    because they are different lessons from different tickets.

    Mutation: collapse record_key to a bare ``topic`` and this test goes RED,
    because the archived twin's topic would mask the orphan (a silent
    false-green, which the 19 prior tests did not catch).
    """
    repo = _make_repo(tmp_path)
    archived_twin = _obs("manager-review-rubric", "WOT-2026-555a")
    orphan = _obs("manager-review-rubric", "WOT-2026-666b")
    _write(repo / OBS_REL, [archived_twin, orphan])
    _write(repo / _archive_rel(), [archived_twin])  # only the twin travelled

    r = _run(repo)
    assert r.returncode == EXIT_ORPHANS, (
        "a lesson sharing a topic with an ARCHIVED one but under a DIFFERENT "
        "source_ticket is still an orphan; the archived twin must not mask it. "
        f"got {r.returncode}. stdout: {r.stdout} stderr: {r.stderr}"
    )
    assert "WOT-2026-666b" in r.stdout, "the un-archived lesson must be named"
    assert "WOT-2026-555a" not in r.stdout, (
        "the archived twin has travelled; it must NOT be reported as an orphan"
    )


# ---------------------------------------------------------------------------
# WOT-2026-026f / D2-D3: el remedio deja de ser NO-OP y las dos politicas
# (038j y memory_upload.md) se citan mutuamente en vez de contradecirse.
# ---------------------------------------------------------------------------


def _remedy_text(root) -> str:
    import io
    from contextlib import redirect_stdout

    import scripts.check_portable_memory_promotion as guard

    buf = io.StringIO()
    with redirect_stdout(buf):
        guard._print_remedy(root)
    return buf.getvalue()


def test_canonical_remedy_offers_the_curated_route_not_a_noop(tmp_path, monkeypatch):
    """D2: en un canonico el remedio debe ofrecer --promote-id, NO un no-op.

    El defecto original: el guard imprimia `reconcile --source <canonico> --apply`,
    que en source==dest sale exit 0 SIN escribir. Recomendar eso es la trampa del
    "exit 0 = no hice nada" DENTRO de la barrera que existe para evitarla.
    """
    import scripts.check_portable_memory_promotion as guard

    monkeypatch.setattr(guard, "is_canonical", lambda root: True)

    text = _remedy_text(tmp_path)

    assert "--promote-id" in text, "el remedio del canonico debe ofrecer la via curada"
    assert "memory_consolidate.py --apply" in text, "y la via por antiguedad"


def test_canonical_remedy_no_longer_claims_recent_cannot_be_promoted(
    tmp_path, monkeypatch
):
    """D3: se retira la clausula 'una leccion RECIENTE NO se puede forzar'.

    DEC-026F-001 la invalida con evidencia medida (2 lecciones de 45 min promovidas
    con --strict exit 0). Lo que NO se puede es promoverla POR ANTIGUEDAD.
    """
    import scripts.check_portable_memory_promotion as guard

    monkeypatch.setattr(guard, "is_canonical", lambda root: True)

    text = _remedy_text(tmp_path)

    assert "espera a que cruce el umbral" not in text, (
        "sigue diciendo que hay que esperar: esa clausula esta invalidada"
    )
    assert "POR ANTIGUEDAD" in text or "por ANTIGUEDAD" in text


def test_038j_and_memory_upload_cite_each_other(tmp_path):
    """D3: las dos superficies de la politica se CITAN, para no re-divergir.

    Sin cita mutua, cada una puede evolucionar sola y volver a contradecirse: eso
    es exactamente lo que produjo WOT-2026-026f.
    """
    root = Path(__file__).resolve().parents[2]
    guard_src = (root / "scripts" / "check_portable_memory_promotion.py").read_text(
        encoding="utf-8"
    )
    prompt_src = (root / "prompts" / "memory_upload.md").read_text(encoding="utf-8")

    assert "memory_upload.md" in guard_src, "el guard debe citar el prompt"
    assert "check_portable_memory_promotion" in prompt_src, (
        "el prompt debe citar el guard"
    )
    assert "DEC-026F-001" in guard_src and "DEC-026F-001" in prompt_src


def test_the_two_lessons_promoted_on_20260721_are_still_in_the_archive():
    """D4: las 2 lecciones ya promovidas SE CONSERVAN (revertirlas esta PROHIBIDO).

    DEC-026F-001 lo declara explicitamente: son estado valido, no deuda.
    """
    root = Path(__file__).resolve().parents[2]
    archive = root / ".agent" / "runtime" / "memory" / "archive"
    body = "\n".join(
        p.read_text(encoding="utf-8") for p in archive.glob("observations.*.jsonl")
    )

    for obs_id in (
        "obs-parada-humana-requiere-group-stop-report",
        "obs-profundidad-auditoria-proporcional-al-riesgo",
    ):
        assert obs_id in body, (
            f"leccion revertida (PROHIBIDO por DEC-026F-001): {obs_id}"
        )
