"""Contract tests for scripts/check_portable_memory_promotion.py (WOT-2026-022z).

The guard detects ORPHANED LESSONS: a hand-written observation that lives only in
`.agent/runtime/memory/observations.jsonl` (GITIGNORED in every worktree, so no push
moves it) and is absent from the tracked archive
`.agent/runtime/memory/archive/observations.YYYY-MM.jsonl` -- the only file that
actually travels. The session believes it promoted the lesson; it never leaves the box.

Load-bearing properties:

1. The verdict is decided by TWO conditions ANDed: "is a lesson" AND "not in the
   archive". Test (f) isolates the branch: autogenerated telemetry absent from the
   archive is NOT an orphan (it is not meant to travel) -> exit 0.
   Mutation: neutralize the archive comparison (treat the archive set as containing
   everything) -> the orphan test goes RED.

2. Exit codes are DIFFERENTIATED: 0 = clean, 1 = the TOOL failed, 4 = there ARE
   orphans. Collapsing 4 into 1 (or into 0) makes the guard useless as an automated
   barrier: "there are orphans" is a FINDING, not a broken tool.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


SCRIPT = (
    Path(__file__).resolve().parents[2]
    / "scripts"
    / "check_portable_memory_promotion.py"
)
OBS_REL = Path(".agent/runtime/memory/observations.jsonl")
ARCHIVE_DIR_REL = Path(".agent/runtime/memory/archive")

EXIT_OK = 0
EXIT_TOOL_ERROR = 1
EXIT_ORPHANS = 4


def _archive_rel(month: str | None = None) -> Path:
    stamp = month or datetime.now(timezone.utc).strftime("%Y-%m")
    return ARCHIVE_DIR_REL / f"observations.{stamp}.jsonl"


def _obs(topic: str, ticket: str, domain: str = "review-quality") -> dict:
    return {
        "timestamp": "2026-07-12T10:00:00Z",
        "topic": topic,
        "signal": f"senal de {topic} para {ticket}",
        "source": ticket,
        "source_ticket": ticket,
        "applies_to": "all",
        "confidence": 0.9,
        "domain": domain,
    }


def _write(path: Path, records: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(json.dumps(r) + "\n" for r in records), encoding="utf-8", newline="\n"
    )


def _make_repo(tmp_path: Path) -> Path:
    """A real git repo (the guard refuses to audit a non-repo: exit 1)."""
    repo = tmp_path / "repo"
    repo.mkdir()

    def run(*a: str) -> None:
        subprocess.run(
            ["git", *a], cwd=str(repo), capture_output=True, text=True, check=True
        )

    run("init", "-b", "main")
    run("config", "user.email", "t@t.t")
    run("config", "user.name", "t")
    (repo / "README").write_text("x", encoding="utf-8")
    run("add", "-A")
    run("commit", "-m", "base")
    return repo


def _run(repo: Path) -> subprocess.CompletedProcess:
    # returncode read directly -- never `$?` after a pipe.
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--project-root", str(repo)],
        capture_output=True,
        text=True,
        check=False,
    )


def test_lesson_absent_from_archive_is_an_orphan_and_is_named(tmp_path: Path) -> None:
    """(d) THE GUARD'S TEST: a lesson only in the gitignored runtime file is an
    orphan -> exit 4, and the output NAMES it (a mute count is not actionable).

    Mutation: neutralize the archive comparison -> RED.
    """
    repo = _make_repo(tmp_path)
    _write(repo / OBS_REL, [_obs("leccion-huerfana", "WOT-2026-111a")])
    _write(repo / _archive_rel(), [])

    r = _run(repo)

    assert r.returncode == EXIT_ORPHANS, (
        "a lesson present in the gitignored observations.jsonl and ABSENT from the "
        f"tracked archive must be reported as an orphan (exit 4); got {r.returncode}. "
        f"stdout: {r.stdout} stderr: {r.stderr}"
    )
    assert "leccion-huerfana" in r.stdout, "the guard must NAME each orphan"
    assert "WOT-2026-111a" in r.stdout, "the guard must report the source_ticket"
    assert "reconcile_portable_memory.py" in r.stdout, "must point at the remedy"


def test_lesson_present_in_archive_is_clean(tmp_path: Path) -> None:
    """(e) The same lesson, already in the tracked archive -> exit 0."""
    repo = _make_repo(tmp_path)
    lesson = _obs("leccion-promovida", "WOT-2026-222b")
    _write(repo / OBS_REL, [lesson])
    _write(repo / _archive_rel(), [lesson])

    r = _run(repo)
    assert r.returncode == EXIT_OK, (
        f"a lesson already in the archive has travelled; got {r.returncode}. "
        f"stdout: {r.stdout}"
    )


def test_lesson_archived_in_another_month_is_clean(tmp_path: Path) -> None:
    """The archive set is built from ALL months, not just the current one: a lesson
    promoted in a previous month already travelled."""
    repo = _make_repo(tmp_path)
    lesson = _obs("leccion-de-otro-mes", "WOT-2026-333c")
    _write(repo / OBS_REL, [lesson])
    _write(repo / _archive_rel("2020-01"), [lesson])

    r = _run(repo)
    assert r.returncode == EXIT_OK, r.stdout + r.stderr


def test_autogenerated_telemetry_absent_from_archive_is_not_an_orphan(
    tmp_path: Path,
) -> None:
    """(f) BRANCH ISOLATION (021u lesson): the verdict needs BOTH conditions.

    Telemetry (`architecture` / `ticket-completion`, emitted by
    session_close_observations.py on every close) is NOT a portable lesson: it is not
    meant to travel, so its absence from the archive is NOT a finding. If the guard
    only checked "absent from the archive", this would be a false positive -- and the
    guard would fire on every single session.
    """
    repo = _make_repo(tmp_path)
    _write(
        repo / OBS_REL,
        [
            _obs("architecture", "WOT-2026-444d"),
            _obs("ticket-completion", "WOT-2026-444d"),
        ],
    )
    _write(repo / _archive_rel(), [])

    r = _run(repo)
    assert r.returncode == EXIT_OK, (
        "autogenerated telemetry absent from the archive is NOT an orphan; the "
        f"verdict requires 'is a lesson' AND 'not archived'. got {r.returncode}. "
        f"stdout: {r.stdout}"
    )


def test_non_repo_root_is_a_tool_error_not_a_finding(tmp_path: Path) -> None:
    """Exit 1 (tool failure) must NOT be confused with exit 4 (there are orphans).

    REFUTED PREMISE (found while writing this test): `tmp_path` lives INSIDE the motor
    tree (tests/sandbox/test_runtime/...), so a plain directory there still answers
    `git rev-parse --git-dir` with the MOTOR's .git. "Being inside a git repo" is not
    enough: the guard requires --project-root to BE the toplevel, otherwise it would
    happily audit a non-repo path and call it clean.
    """
    not_a_repo = tmp_path / "plain"
    (not_a_repo / OBS_REL).parent.mkdir(parents=True)
    _write(not_a_repo / OBS_REL, [_obs("x", "WOT-2026-555e")])

    r = _run(not_a_repo)
    assert r.returncode == EXIT_TOOL_ERROR, (
        f"a path that is not a git checkout root is a TOOL failure (exit 1), not a "
        f"finding; got {r.returncode}"
    )


def test_corrupt_jsonl_is_a_tool_error(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    obs = repo / OBS_REL
    obs.parent.mkdir(parents=True, exist_ok=True)
    obs.write_bytes(b"{not json\n")

    r = _run(repo)
    assert r.returncode == EXIT_TOOL_ERROR, (
        f"an unreadable memory file is a TOOL failure (exit 1); got {r.returncode}"
    )


def test_no_runtime_memory_is_clean(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    r = _run(repo)
    assert r.returncode == EXIT_OK, r.stdout + r.stderr


def test_same_topic_different_source_ticket_is_still_an_orphan(tmp_path: Path) -> None:
    """WOT-2026-023g: record_key is (topic, source_ticket), NEVER topic alone.

    Two lessons share a topic but differ in source_ticket; one is already in
    the archive, the other is only in the gitignored runtime. The guard must
    STILL flag the un-archived one -- the archived twin does NOT cover it,
    because they are different lessons from different tickets.

    Mutation: collapse record_key to a bare ``topic`` and this test goes RED,
    because the archived twin's topic would mask the orphan (a silent
    false-green, which the 19 prior tests did not catch).
    """
    repo = _make_repo(tmp_path)
    archived_twin = _obs("manager-review-rubric", "WOT-2026-555a")
    orphan = _obs("manager-review-rubric", "WOT-2026-666b")
    _write(repo / OBS_REL, [archived_twin, orphan])
    _write(repo / _archive_rel(), [archived_twin])  # only the twin travelled

    r = _run(repo)
    assert r.returncode == EXIT_ORPHANS, (
        "a lesson sharing a topic with an ARCHIVED one but under a DIFFERENT "
        "source_ticket is still an orphan; the archived twin must not mask it. "
        f"got {r.returncode}. stdout: {r.stdout} stderr: {r.stderr}"
    )
    assert "WOT-2026-666b" in r.stdout, "the un-archived lesson must be named"
    assert "WOT-2026-555a" not in r.stdout, (
        "the archived twin has travelled; it must NOT be reported as an orphan"
    )
