"""Contract tests for scripts/reconcile_portable_memory.py (WOT-2026-022y/022z).

The reconciler promotes hand-written observations from a non-canonical worktree
to the canonical checkout. `.agent/runtime/memory/observations.jsonl` is
working-tree content (not git metadata) and GITIGNORED in EVERY worktree: no
commit picks it up and no push moves it, so writing memory there looks like
promotion and is not.

The three load-bearing properties:

0. (022z) The promotion target is the TRACKED ARCHIVE
   `.agent/runtime/memory/archive/observations.YYYY-MM.jsonl` -- the only file
   that actually travels. 022y wrote to `observations.jsonl` (gitignored): it
   "reconciled" a file no push moves. Mutation: write to observations.jsonl
   again -> `test_promotes_hand_written_lessons_into_the_tracked_archive` -> RED.

1. AUTOGENERATED records are EXCLUDED. `session_close_observations.py` emits
   `architecture` / `ticket-completion` on every session close (mechanical
   telemetry, e.g. "Ticket X completado: Unknown"). The canonical checkout
   already accumulates its own; copying another worktree's would pollute the
   memory with noise. Mutation: drop the exclusion -> the telemetry gets
   promoted -> RED.

2. Identity is (topic, source_ticket), NEVER `topic` alone. `topic` is a reused
   generic label (`architecture` has dozens of records, one per ticket).
   Deduplicating by `topic` would discard legitimate records as "duplicates".
   Mutation: dedupe by topic -> a distinct-ticket record is dropped -> RED.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest


SCRIPT = (
    Path(__file__).resolve().parents[2] / "scripts" / "reconcile_portable_memory.py"
)
OBS_REL = Path(".agent/runtime/memory/observations.jsonl")
ARCHIVE_DIR_REL = Path(".agent/runtime/memory/archive")


def _archive_rel(month: str | None = None) -> Path:
    """The tracked archive file for `month` (default: current UTC month)."""
    stamp = month or datetime.now(timezone.utc).strftime("%Y-%m")
    return ARCHIVE_DIR_REL / f"observations.{stamp}.jsonl"


def _obs(topic: str, ticket: str, domain: str = "review-quality") -> dict:
    return {
        "timestamp": "2026-07-12T10:00:00Z",
        "topic": topic,
        "signal": f"senal de {topic} para {ticket}",
        "source": ticket,
        "source_ticket": ticket,
        "applies_to": "all",
        "confidence": 0.9,
        "domain": domain,
        "recommended_followup": "n/a",
    }


def _write(path: Path, records: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(json.dumps(r) + "\n" for r in records), encoding="utf-8", newline="\n"
    )


def _make_worktree_pair(tmp_path: Path) -> tuple[Path, Path]:
    """A canonical checkout + a linked worktree, the real topology under test."""
    canon = tmp_path / "canon"
    canon.mkdir()

    def run(*a: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *a],
            cwd=str(canon),
            capture_output=True,
            text=True,
            check=True,
        )

    run("init", "-b", "main")
    run("config", "user.email", "t@t.t")
    run("config", "user.name", "t")
    (canon / "README").write_text("x", encoding="utf-8")
    run("add", "-A")
    run("commit", "-m", "base")

    linked = tmp_path / "linked"
    run("worktree", "add", str(linked))
    return canon, linked


def _run(source: Path, apply: bool = True) -> subprocess.CompletedProcess:
    args = [sys.executable, str(SCRIPT), "--source", str(source)]
    if apply:
        args.append("--apply")
    # returncode read directly -- never `$?` after a pipe.
    return subprocess.run(args, capture_output=True, text=True, check=False)


def _load(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    return [
        json.loads(x)
        for x in path.read_text(encoding="utf-8").splitlines()
        if x.strip()
    ]


def test_canonical_checkout_is_resolved_from_git_common_dir(tmp_path: Path) -> None:
    """The canonical checkout is resolved by --git-common-dir, not by a heuristic
    on the --git-dir string (searching for "worktrees/" works by accident of
    naming, not by construction)."""
    canon, linked = _make_worktree_pair(tmp_path)
    sys.path.insert(0, str(SCRIPT.parent))
    try:
        import reconcile_portable_memory as mod

        assert mod.is_canonical(canon) is True
        assert mod.is_canonical(linked) is False
        assert mod.canonical_checkout(linked) == canon.resolve()
    finally:
        sys.path.pop(0)


def test_promotes_hand_written_lessons_into_the_tracked_archive(tmp_path: Path) -> None:
    """THE TICKET'S TEST (022z). The promotion must land in the TRACKED ARCHIVE.

    `observations.jsonl` is gitignored in every worktree: writing there promotes
    NOTHING (no commit picks it up, no push moves it). The only portable vehicle is
    `archive/observations.YYYY-MM.jsonl`, which IS versioned.

    Mutation: make the reconciler append to `observations.jsonl` again -> RED.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    _write(canon / _archive_rel(), [_obs("existing-lesson", "WOT-2026-001a")])
    _write(linked / OBS_REL, [_obs("nueva-leccion", "WOT-2026-002b")])

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    archived = [x["topic"] for x in _load(canon / _archive_rel())]
    assert "nueva-leccion" in archived, (
        "the hand-written lesson must land in the TRACKED archive; writing it to the "
        "gitignored observations.jsonl promotes nothing"
    )
    assert "existing-lesson" in archived, (
        "pre-existing archive records must not be lost"
    )


def test_dedup_crosses_all_archive_months(tmp_path: Path) -> None:
    """A lesson promoted in a PREVIOUS month already travelled: it must not be
    re-promoted into the current month's archive file.

    The dedup set is built from ALL `archive/*.jsonl`, not just the current month.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    old = _obs("leccion-vieja", "WOT-2026-010a")
    _write(
        canon / _archive_rel("2020-01"), [old]
    )  # a month that is NOT the current one
    _write(linked / OBS_REL, [old])

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    assert not (canon / _archive_rel()).exists() or not [
        x for x in _load(canon / _archive_rel()) if x["topic"] == "leccion-vieja"
    ], "a lesson already archived in ANOTHER month must NOT be re-promoted"
    assert len(_load(canon / _archive_rel("2020-01"))) == 1


@pytest.mark.parametrize("auto_topic", ["architecture", "ticket-completion"])
def test_autogenerated_records_are_excluded(tmp_path: Path, auto_topic: str) -> None:
    """LOAD-BEARING: telemetry emitted on every session close must NOT be promoted.

    The canonical checkout generates its own; importing another worktree's would
    pollute the portable memory with noise (one such record literally reads
    "completado: Unknown").

    Mutation: remove AUTOGENERATED_TOPICS from the filter -> this goes RED.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    _write(canon / _archive_rel(), [])
    _write(
        linked / OBS_REL,
        [
            _obs(auto_topic, "WOT-2026-009z"),  # telemetry -> must NOT travel
            _obs("leccion-real", "WOT-2026-009z"),  # lesson    -> must travel
        ],
    )

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    topics = [x["topic"] for x in _load(canon / _archive_rel())]
    assert auto_topic not in topics, (
        f"{auto_topic!r} is autogenerated telemetry (session_close_observations.py) "
        f"and must NEVER be promoted across worktrees"
    )
    assert "leccion-real" in topics, "the real lesson must still be promoted"


def test_identity_is_topic_plus_source_ticket_not_topic_alone(tmp_path: Path) -> None:
    """LOAD-BEARING: `topic` is NOT an identity key.

    A generic topic is reused across tickets. If the reconciler deduped by topic,
    it would discard a legitimate record from a DIFFERENT ticket as a "duplicate"
    -- silent data loss, which is the exact failure class this ticket exists to fix.

    Mutation: key on `topic` alone -> the WOT-...-777b record is dropped -> RED.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    # Same topic, DIFFERENT ticket: these are distinct records, not duplicates.
    _write(canon / _archive_rel(), [_obs("shared-topic", "WOT-2026-666a")])
    _write(linked / OBS_REL, [_obs("shared-topic", "WOT-2026-777b")])

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    tickets = [x["source_ticket"] for x in _load(canon / _archive_rel())]
    assert "WOT-2026-666a" in tickets, "the pre-existing record must survive"
    assert "WOT-2026-777b" in tickets, (
        "a record with the same topic but a DIFFERENT source_ticket is a distinct "
        "record and must be promoted; deduping by topic alone loses it"
    )


def test_refuses_to_write_onto_an_invalid_destination(tmp_path: Path) -> None:
    """LOAD-BEARING (fail-closed): if the destination memory does NOT pass
    validate_observations --strict, the reconciler must REFUSE to write.

    Appending onto an already-corrupt file would bury the corruption under new
    records and make the damage harder to attribute. Refusing keeps the failure
    visible and attributable.

    This test exists because the mutation caught its absence: removing the
    fail-closed check left all other tests GREEN (a property with no mutation
    that negates it is not a barrier).

    Mutation: drop the `if rc != 0: return 1` guard -> the write proceeds -> RED.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    # A record missing the mandatory `domain` field -> --strict rejects the file.
    bad = _obs("corrupto", "WOT-2026-888a")
    del bad["domain"]
    _write(canon / _archive_rel(), [bad])
    _write(linked / OBS_REL, [_obs("leccion-nueva", "WOT-2026-999b")])

    before = _load(canon / _archive_rel())
    r = _run(linked)

    assert r.returncode == 1, (
        "the reconciler must FAIL (exit 1) when the destination does not validate "
        f"--strict; got {r.returncode}. stdout: {r.stdout}"
    )
    assert _load(canon / _archive_rel()) == before, (
        "nothing may be written onto an invalid destination memory (fail-closed)"
    )
    topics = [x["topic"] for x in _load(canon / _archive_rel())]
    assert "leccion-nueva" not in topics


def test_existing_key_is_not_overwritten(tmp_path: Path) -> None:
    """A key already present in the destination is reported, never overwritten
    (no blind merge). The destination's version wins."""
    canon, linked = _make_worktree_pair(tmp_path)
    keep = _obs("colision", "WOT-2026-555a")
    keep["signal"] = "LA VERSION DEL CANONICO"
    other = _obs("colision", "WOT-2026-555a")
    other["signal"] = "la version de la worktree"
    _write(canon / _archive_rel(), [keep])
    _write(linked / OBS_REL, [other])

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    recs = _load(canon / _archive_rel())
    assert len(recs) == 1, "must not append a colliding key"
    assert recs[0]["signal"] == "LA VERSION DEL CANONICO", "must not overwrite"


def test_is_idempotent(tmp_path: Path) -> None:
    """Running twice must not duplicate: the second pass promotes nothing."""
    canon, linked = _make_worktree_pair(tmp_path)
    _write(canon / _archive_rel(), [])
    _write(linked / OBS_REL, [_obs("una-leccion", "WOT-2026-003c")])

    assert _run(linked).returncode == 0
    first = len(_load(canon / _archive_rel()))
    assert _run(linked).returncode == 0
    assert len(_load(canon / _archive_rel())) == first, "second run must not duplicate"


def test_source_equal_to_canonical_is_a_noop(tmp_path: Path) -> None:
    """Reconciling the canonical checkout against itself does nothing."""
    canon, _ = _make_worktree_pair(tmp_path)
    _write(canon / OBS_REL, [_obs("x", "WOT-2026-004d")])
    r = _run(canon)
    assert r.returncode == 0
    assert "YA es el checkout canonico" in r.stdout
    assert len(_load(canon / OBS_REL)) == 1


def test_corrupt_archive_fails_closed_with_a_message_not_a_traceback(
    tmp_path: Path,
) -> None:
    """A syntactically broken archive is an ERROR, not a crash (WOT-2026-022z).

    load_records() used to let json.JSONDecodeError escape, so a broken archive aborted
    the run with a TRACEBACK: fail-closed de facto (nothing written) but the non-zero
    exit arrived by CRASH, not by barrier. "The script blew up" is indistinguishable
    from a bug in the script itself, and the operator got no filename.

    ORDER OF BARRIERS (found by probe, not by reading): --strict runs BEFORE anything is
    parsed, so an unreadable archive is now rejected by validate_dest_archive and never
    reaches load_records. That is the SAFER order -- validate, then parse -- so this test
    asserts the PROPERTY (rejected, named, nothing written, no crash) rather than which
    specific barrier fired. CorruptMemoryError remains the backstop for any record that
    slips past validation.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    broken = canon / _archive_rel("2020-01")
    broken.parent.mkdir(parents=True, exist_ok=True)
    broken.write_text("{esto no es json\n", encoding="utf-8")
    _write(linked / OBS_REL, [_obs("leccion", "WOT-2026-005e")])

    r = _run(linked)

    assert r.returncode == 1, "un archive ilegible debe fail-closed"
    assert "fail-closed" in r.stdout
    assert "2020-01" in r.stdout, "el error debe NOMBRAR el fichero"
    assert "Traceback" not in r.stderr, "debe salir por la barrera, no por crash"
    assert not (canon / _archive_rel()).exists(), "no debe escribir nada"


def test_strict_validation_covers_every_archive_that_feeds_the_dedup(
    tmp_path: Path,
) -> None:
    """A PAST month with an invalid domain is rejected too (WOT-2026-022z).

    BRANCH ISOLATION (leccion 021u): validating only the file being WRITTEN (the current
    month) left a hole -- an archive from a PREVIOUS month with a `domain` outside the
    VALID_DOMAINS enum is perfectly parseable, so it fed the dedup set without ever
    passing --strict. The dedup DECIDES what gets promoted; feeding it memory the
    barrier never inspected is trusting unvalidated data. The invalid domain lives ONLY
    in the past month here, so the current-month check alone cannot catch it: this test
    goes red the moment validation stops covering every archive that feeds the dedup.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    bad = _obs("leccion-vieja", "WOT-2026-006f")
    bad["domain"] = "dominio-que-no-existe-en-el-enum"
    _write(canon / _archive_rel("2020-01"), [bad])
    _write(linked / OBS_REL, [_obs("leccion-nueva", "WOT-2026-007g")])

    r = _run(linked)

    assert r.returncode == 1, "un archive de mes ANTERIOR invalido debe fail-closed"
    assert "NO valida --strict" in r.stdout
    assert "2020-01" in r.stdout, "el error debe NOMBRAR el archive culpable"
    assert not (canon / _archive_rel()).exists(), "no debe escribir nada"
