"""Contract tests for scripts/reconcile_portable_memory.py (WOT-2026-022y/022z).

The reconciler promotes hand-written observations from a non-canonical worktree
to the canonical checkout. `.agent/runtime/memory/observations.jsonl` is
working-tree content (not git metadata) and GITIGNORED in EVERY worktree: no
commit picks it up and no push moves it, so writing memory there looks like
promotion and is not.

The three load-bearing properties:

0. (022z) The promotion target is the TRACKED ARCHIVE
   `.agent/runtime/memory/archive/observations.YYYY-MM.jsonl` -- the only file
   that actually travels. 022y wrote to `observations.jsonl` (gitignored): it
   "reconciled" a file no push moves. Mutation: write to observations.jsonl
   again -> `test_promotes_hand_written_lessons_into_the_tracked_archive` -> RED.

1. AUTOGENERATED records are EXCLUDED. `session_close_observations.py` emits
   `architecture` / `ticket-completion` on every session close (mechanical
   telemetry, e.g. "Ticket X completado: Unknown"). The canonical checkout
   already accumulates its own; copying another worktree's would pollute the
   memory with noise. Mutation: drop the exclusion -> the telemetry gets
   promoted -> RED.

2. Identity is (topic, source_ticket), NEVER `topic` alone. `topic` is a reused
   generic label (`architecture` has dozens of records, one per ticket).
   Deduplicating by `topic` would discard legitimate records as "duplicates".
   Mutation: dedupe by topic -> a distinct-ticket record is dropped -> RED.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest


SCRIPT = (
    Path(__file__).resolve().parents[2] / "scripts" / "reconcile_portable_memory.py"
)
OBS_REL = Path(".agent/runtime/memory/observations.jsonl")
ARCHIVE_DIR_REL = Path(".agent/runtime/memory/archive")


def _archive_rel(month: str | None = None) -> Path:
    """The tracked archive file for `month` (default: current UTC month)."""
    stamp = month or datetime.now(timezone.utc).strftime("%Y-%m")
    return ARCHIVE_DIR_REL / f"observations.{stamp}.jsonl"


def _obs(topic: str, ticket: str, domain: str = "review-quality") -> dict:
    return {
        "timestamp": "2026-07-12T10:00:00Z",
        "topic": topic,
        "signal": f"senal de {topic} para {ticket}",
        "source": ticket,
        "source_ticket": ticket,
        "applies_to": "all",
        "confidence": 0.9,
        "domain": domain,
        "recommended_followup": "n/a",
    }


def _write(path: Path, records: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(json.dumps(r) + "\n" for r in records), encoding="utf-8", newline="\n"
    )


def _make_worktree_pair(tmp_path: Path) -> tuple[Path, Path]:
    """A canonical checkout + a linked worktree, the real topology under test."""
    canon = tmp_path / "canon"
    canon.mkdir()

    def run(*a: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *a],
            cwd=str(canon),
            capture_output=True,
            text=True,
            check=True,
        )

    run("init", "-b", "main")
    run("config", "user.email", "t@t.t")
    run("config", "user.name", "t")
    (canon / "README").write_text("x", encoding="utf-8")
    run("add", "-A")
    run("commit", "-m", "base")

    linked = tmp_path / "linked"
    run("worktree", "add", str(linked))
    return canon, linked


def _make_multi_worktree_topology(tmp_path: Path) -> tuple[Path, Path, Path]:
    """Reproduces the REAL machine topology (WOT-2026-025m): a primary checkout
    left DETACHED, a linked worktree carrying `main` (where memory is actually
    published), and a third linked worktree that plays the `--source`.

    `git worktree add` refuses the same branch checked out twice, so the
    primary must be detached BEFORE `main` is added to the second worktree
    (mirrors `_make_git_tree` in test_check_worktree_topology.py).

    Returns (primary_detached, dev_with_main, source_worktree).
    """
    primary = tmp_path / "primary"
    primary.mkdir()

    def run(cwd: Path, *a: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *a], cwd=str(cwd), capture_output=True, text=True, check=True
        )

    run(primary, "init", "-b", "main")
    run(primary, "config", "user.email", "t@t.t")
    run(primary, "config", "user.name", "t")
    (primary / "README").write_text("x", encoding="utf-8")
    run(primary, "add", "-A")
    run(primary, "commit", "-m", "base")
    run(primary, "checkout", "--detach", "main")

    dev = tmp_path / "dev"
    run(primary, "worktree", "add", str(dev), "main")

    source = tmp_path / "source"
    run(primary, "worktree", "add", "-b", "source-branch", str(source))

    return primary, dev, source


def _run(source: Path, apply: bool = True) -> subprocess.CompletedProcess:
    args = [sys.executable, str(SCRIPT), "--source", str(source)]
    if apply:
        args.append("--apply")
    # returncode read directly -- never `$?` after a pipe.
    return subprocess.run(args, capture_output=True, text=True, check=False)


def _load(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    return [
        json.loads(x)
        for x in path.read_text(encoding="utf-8").splitlines()
        if x.strip()
    ]


def test_canonical_checkout_is_the_worktree_carrying_main(tmp_path: Path) -> None:
    """The canonical checkout is the worktree carrying `main` (resolved from
    `git worktree list --porcelain`), NOT whatever `--git-common-dir` points at
    (WOT-2026-025m: the old heuristic silently resolved to a detached primary).
    In this fixture the canonical checkout has `main` checked out directly, so it
    is the sole match and both the old and new mechanisms agree here."""
    canon, linked = _make_worktree_pair(tmp_path)
    sys.path.insert(0, str(SCRIPT.parent))
    try:
        import reconcile_portable_memory as mod

        assert mod.is_canonical(canon) is True
        assert mod.is_canonical(linked) is False
        assert mod.canonical_checkout(linked) == canon.resolve()
    finally:
        sys.path.pop(0)


def test_promotes_hand_written_lessons_into_the_tracked_archive(tmp_path: Path) -> None:
    """THE TICKET'S TEST (022z). The promotion must land in the TRACKED ARCHIVE.

    `observations.jsonl` is gitignored in every worktree: writing there promotes
    NOTHING (no commit picks it up, no push moves it). The only portable vehicle is
    `archive/observations.YYYY-MM.jsonl`, which IS versioned.

    Mutation: make the reconciler append to `observations.jsonl` again -> RED.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    _write(canon / _archive_rel(), [_obs("existing-lesson", "WOT-2026-001a")])
    _write(linked / OBS_REL, [_obs("nueva-leccion", "WOT-2026-002b")])

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    archived = [x["topic"] for x in _load(canon / _archive_rel())]
    assert "nueva-leccion" in archived, (
        "the hand-written lesson must land in the TRACKED archive; writing it to the "
        "gitignored observations.jsonl promotes nothing"
    )
    assert "existing-lesson" in archived, (
        "pre-existing archive records must not be lost"
    )


def test_dedup_crosses_all_archive_months(tmp_path: Path) -> None:
    """A lesson promoted in a PREVIOUS month already travelled: it must not be
    re-promoted into the current month's archive file.

    The dedup set is built from ALL `archive/*.jsonl`, not just the current month.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    old = _obs("leccion-vieja", "WOT-2026-010a")
    _write(
        canon / _archive_rel("2020-01"), [old]
    )  # a month that is NOT the current one
    _write(linked / OBS_REL, [old])

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    assert not (canon / _archive_rel()).exists() or not [
        x for x in _load(canon / _archive_rel()) if x["topic"] == "leccion-vieja"
    ], "a lesson already archived in ANOTHER month must NOT be re-promoted"
    assert len(_load(canon / _archive_rel("2020-01"))) == 1


@pytest.mark.parametrize("auto_topic", ["architecture", "ticket-completion"])
def test_autogenerated_records_are_excluded(tmp_path: Path, auto_topic: str) -> None:
    """LOAD-BEARING: telemetry emitted on every session close must NOT be promoted.

    The canonical checkout generates its own; importing another worktree's would
    pollute the portable memory with noise (one such record literally reads
    "completado: Unknown").

    Mutation: remove AUTOGENERATED_TOPICS from the filter -> this goes RED.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    _write(canon / _archive_rel(), [])
    _write(
        linked / OBS_REL,
        [
            _obs(auto_topic, "WOT-2026-009z"),  # telemetry -> must NOT travel
            _obs("leccion-real", "WOT-2026-009z"),  # lesson    -> must travel
        ],
    )

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    topics = [x["topic"] for x in _load(canon / _archive_rel())]
    assert auto_topic not in topics, (
        f"{auto_topic!r} is autogenerated telemetry (session_close_observations.py) "
        f"and must NEVER be promoted across worktrees"
    )
    assert "leccion-real" in topics, "the real lesson must still be promoted"


def test_identity_is_topic_plus_source_ticket_not_topic_alone(tmp_path: Path) -> None:
    """LOAD-BEARING: `topic` is NOT an identity key.

    A generic topic is reused across tickets. If the reconciler deduped by topic,
    it would discard a legitimate record from a DIFFERENT ticket as a "duplicate"
    -- silent data loss, which is the exact failure class this ticket exists to fix.

    Mutation: key on `topic` alone -> the WOT-...-777b record is dropped -> RED.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    # Same topic, DIFFERENT ticket: these are distinct records, not duplicates.
    _write(canon / _archive_rel(), [_obs("shared-topic", "WOT-2026-666a")])
    _write(linked / OBS_REL, [_obs("shared-topic", "WOT-2026-777b")])

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    tickets = [x["source_ticket"] for x in _load(canon / _archive_rel())]
    assert "WOT-2026-666a" in tickets, "the pre-existing record must survive"
    assert "WOT-2026-777b" in tickets, (
        "a record with the same topic but a DIFFERENT source_ticket is a distinct "
        "record and must be promoted; deduping by topic alone loses it"
    )


def test_refuses_to_write_onto_an_invalid_destination(tmp_path: Path) -> None:
    """LOAD-BEARING (fail-closed): if the destination memory does NOT pass
    validate_observations --strict, the reconciler must REFUSE to write.

    Appending onto an already-corrupt file would bury the corruption under new
    records and make the damage harder to attribute. Refusing keeps the failure
    visible and attributable.

    This test exists because the mutation caught its absence: removing the
    fail-closed check left all other tests GREEN (a property with no mutation
    that negates it is not a barrier).

    Mutation: drop the `if rc != 0: return 1` guard -> the write proceeds -> RED.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    # A record missing the mandatory `domain` field -> --strict rejects the file.
    bad = _obs("corrupto", "WOT-2026-888a")
    del bad["domain"]
    _write(canon / _archive_rel(), [bad])
    _write(linked / OBS_REL, [_obs("leccion-nueva", "WOT-2026-999b")])

    before = _load(canon / _archive_rel())
    r = _run(linked)

    assert r.returncode == 1, (
        "the reconciler must FAIL (exit 1) when the destination does not validate "
        f"--strict; got {r.returncode}. stdout: {r.stdout}"
    )
    assert _load(canon / _archive_rel()) == before, (
        "nothing may be written onto an invalid destination memory (fail-closed)"
    )
    topics = [x["topic"] for x in _load(canon / _archive_rel())]
    assert "leccion-nueva" not in topics


def test_existing_key_is_not_overwritten(tmp_path: Path) -> None:
    """A key already present in the destination is reported, never overwritten
    (no blind merge). The destination's version wins."""
    canon, linked = _make_worktree_pair(tmp_path)
    keep = _obs("colision", "WOT-2026-555a")
    keep["signal"] = "LA VERSION DEL CANONICO"
    other = _obs("colision", "WOT-2026-555a")
    other["signal"] = "la version de la worktree"
    _write(canon / _archive_rel(), [keep])
    _write(linked / OBS_REL, [other])

    r = _run(linked)
    assert r.returncode == 0, r.stdout + r.stderr

    recs = _load(canon / _archive_rel())
    assert len(recs) == 1, "must not append a colliding key"
    assert recs[0]["signal"] == "LA VERSION DEL CANONICO", "must not overwrite"


def test_is_idempotent(tmp_path: Path) -> None:
    """Running twice must not duplicate: the second pass promotes nothing."""
    canon, linked = _make_worktree_pair(tmp_path)
    _write(canon / _archive_rel(), [])
    _write(linked / OBS_REL, [_obs("una-leccion", "WOT-2026-003c")])

    assert _run(linked).returncode == 0
    first = len(_load(canon / _archive_rel()))
    assert _run(linked).returncode == 0
    assert len(_load(canon / _archive_rel())) == first, "second run must not duplicate"


def test_source_equal_to_canonical_is_a_noop(tmp_path: Path) -> None:
    """Reconciling the canonical checkout against itself does nothing."""
    canon, _ = _make_worktree_pair(tmp_path)
    _write(canon / OBS_REL, [_obs("x", "WOT-2026-004d")])
    r = _run(canon)
    assert r.returncode == 0
    assert "YA es el checkout canonico" in r.stdout
    assert len(_load(canon / OBS_REL)) == 1


def test_corrupt_archive_fails_closed_with_a_message_not_a_traceback(
    tmp_path: Path,
) -> None:
    """A syntactically broken archive is an ERROR, not a crash (WOT-2026-022z).

    load_records() used to let json.JSONDecodeError escape, so a broken archive aborted
    the run with a TRACEBACK: fail-closed de facto (nothing written) but the non-zero
    exit arrived by CRASH, not by barrier. "The script blew up" is indistinguishable
    from a bug in the script itself, and the operator got no filename.

    ORDER OF BARRIERS (found by probe, not by reading): --strict runs BEFORE anything is
    parsed, so an unreadable archive is now rejected by validate_dest_archive and never
    reaches load_records. That is the SAFER order -- validate, then parse -- so this test
    asserts the PROPERTY (rejected, named, nothing written, no crash) rather than which
    specific barrier fired. CorruptMemoryError remains the backstop for any record that
    slips past validation.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    broken = canon / _archive_rel("2020-01")
    broken.parent.mkdir(parents=True, exist_ok=True)
    broken.write_text("{esto no es json\n", encoding="utf-8")
    _write(linked / OBS_REL, [_obs("leccion", "WOT-2026-005e")])

    r = _run(linked)

    assert r.returncode == 1, "un archive ilegible debe fail-closed"
    assert "fail-closed" in r.stdout
    assert "2020-01" in r.stdout, "el error debe NOMBRAR el fichero"
    assert "Traceback" not in r.stderr, "debe salir por la barrera, no por crash"
    assert not (canon / _archive_rel()).exists(), "no debe escribir nada"


def test_canonical_checkout_resolves_to_the_worktree_carrying_main(
    tmp_path: Path,
) -> None:
    """LOAD-BEARING (WOT-2026-025m). In a multi-worktree topology, the checkout
    that PUBLISHES portable memory is the one carrying the `main` branch, not
    whichever worktree `--git-common-dir` happens to point at.

    On the real machine the primary checkout is left DETACHED and `main` lives
    in a linked worktree (`_dev`). The old `--git-common-dir` heuristic always
    resolves to the primary's parent directory regardless of which worktree
    has `main` checked out, so it silently promotes memory into the detached
    checkout -- content that is never on `main` and never gets pushed.

    Mutation: revert to resolving by `--git-common-dir` alone -> this goes RED
    (the archive lands in `primary`, not in `dev`).
    """
    primary, dev, source = _make_multi_worktree_topology(tmp_path)
    _write(dev / _archive_rel(), [_obs("existing-lesson", "WOT-2026-001a")])
    _write(source / OBS_REL, [_obs("nueva-leccion", "WOT-2026-025m")])

    r = _run(source)
    assert r.returncode == 0, r.stdout + r.stderr

    dev_archived = [x["topic"] for x in _load(dev / _archive_rel())]
    assert "nueva-leccion" in dev_archived, (
        "the archive must be written into the worktree that carries `main` "
        f"({dev}), not into the detached primary checkout ({primary}). "
        f"stdout: {r.stdout}"
    )

    primary_archived = [x["topic"] for x in _load(primary / _archive_rel())]
    assert "nueva-leccion" not in primary_archived, (
        "nothing must be written into the detached primary checkout: it does "
        "not carry `main` and is not the portable-memory publication point"
    )


def test_ambiguous_or_missing_main_worktree_fails_closed(tmp_path: Path) -> None:
    """LOAD-BEARING (WOT-2026-025m): if the destination worktree cannot be
    determined UNAMBIGUOUSLY (zero or more than one worktree carries `main`),
    the reconciler must refuse to guess and exit non-zero with a diagnostic,
    rather than silently falling back to some other checkout.
    """
    tmp_path2 = tmp_path / "no_main_case"
    tmp_path2.mkdir()

    def run(cwd: Path, *a: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *a], cwd=str(cwd), capture_output=True, text=True, check=True
        )

    repo = tmp_path2 / "repo"
    repo.mkdir()
    run(repo, "init", "-b", "trunk")
    run(repo, "config", "user.email", "t@t.t")
    run(repo, "config", "user.name", "t")
    (repo / "README").write_text("x", encoding="utf-8")
    run(repo, "add", "-A")
    run(repo, "commit", "-m", "base")
    # No worktree carries `main` here (branch is `trunk`): ambiguity case
    # (zero matches) must fail closed rather than default to some checkout.
    _write(repo / OBS_REL, [_obs("leccion", "WOT-2026-025m")])

    r = _run(repo)
    assert r.returncode != 0, (
        "when no worktree carries `main`, the reconciler must fail-closed "
        f"instead of guessing a destination. stdout: {r.stdout}"
    )


def test_strict_validation_covers_every_archive_that_feeds_the_dedup(
    tmp_path: Path,
) -> None:
    """A PAST month with an invalid domain is rejected too (WOT-2026-022z).

    BRANCH ISOLATION (leccion 021u): validating only the file being WRITTEN (the current
    month) left a hole -- an archive from a PREVIOUS month with a `domain` outside the
    VALID_DOMAINS enum is perfectly parseable, so it fed the dedup set without ever
    passing --strict. The dedup DECIDES what gets promoted; feeding it memory the
    barrier never inspected is trusting unvalidated data. The invalid domain lives ONLY
    in the past month here, so the current-month check alone cannot catch it: this test
    goes red the moment validation stops covering every archive that feeds the dedup.
    """
    canon, linked = _make_worktree_pair(tmp_path)
    bad = _obs("leccion-vieja", "WOT-2026-006f")
    bad["domain"] = "dominio-que-no-existe-en-el-enum"
    _write(canon / _archive_rel("2020-01"), [bad])
    _write(linked / OBS_REL, [_obs("leccion-nueva", "WOT-2026-007g")])

    r = _run(linked)

    assert r.returncode == 1, "un archive de mes ANTERIOR invalido debe fail-closed"
    assert "NO valida --strict" in r.stdout
    assert "2020-01" in r.stdout, "el error debe NOMBRAR el archive culpable"
    assert not (canon / _archive_rel()).exists(), "no debe escribir nada"


# ---------------------------------------------------------------------------
# WOT-2026-026f / D1: via CURADA explicita (--promote-id)
#
# DEC-026F-001 (politica B1): la ANTIGUEDAD (cutoff 30d de memory_consolidate)
# sigue siendo el camino AUTOMATICO, y ADEMAS existe una via curada explicita
# para promover UNA leccion concreta YA, con confirmacion humana.
#
# El agujero que cierra: en un checkout CANONICO (source == dest) el
# reconciliador sale no-op, asi que una leccion reciente del propio canonico no
# tenia NINGUNA via de promocion -- y el promotion-guard recomendaba justo ese
# comando no-op ("exit 0 = no hice nada" DENTRO de la barrera que existe para
# evitarlo).
# ---------------------------------------------------------------------------


def _obs_id(obs_id: str, topic: str, ticket: str) -> dict:
    r = _obs(topic, ticket)
    r["id"] = obs_id
    return r


def _run_promote(source: Path, obs_id: str, apply: bool = True):
    args = [
        sys.executable,
        str(SCRIPT),
        "--source",
        str(source),
        "--promote-id",
        obs_id,
    ]
    if apply:
        args.append("--apply")
    return subprocess.run(args, capture_output=True, text=True, check=False)


def test_promote_id_works_in_the_canonical_checkout(tmp_path: Path) -> None:
    """D1: en el canonico (source==dest), --promote-id SI promueve.

    Es el caso que hoy es un no-op y deja la leccion huerfana para siempre.
    """
    canon, _ = _make_worktree_pair(tmp_path)
    _write(
        canon / OBS_REL,
        [
            _obs_id("obs-uno", "tema-uno", "WOT-2026-026f"),
            _obs_id("obs-dos", "tema-dos", "WOT-2026-026f"),
        ],
    )

    r = _run_promote(canon, "obs-uno")

    assert r.returncode == 0, r.stdout + r.stderr
    promoted = _load(canon / _archive_rel())
    ids = [x.get("id") for x in promoted]
    assert ids == ["obs-uno"], f"solo la leccion pedida se promueve: {ids}"


def test_promote_id_is_deduped_by_id(tmp_path: Path) -> None:
    """D1: promover dos veces la misma leccion NO la duplica (idempotente)."""
    canon, _ = _make_worktree_pair(tmp_path)
    _write(canon / OBS_REL, [_obs_id("obs-uno", "tema-uno", "WOT-2026-026f")])

    first = _run_promote(canon, "obs-uno")
    second = _run_promote(canon, "obs-uno")

    assert first.returncode == 0 and second.returncode == 0
    assert len(_load(canon / _archive_rel())) == 1, "la 2a pasada duplico la leccion"


def test_promote_id_unknown_fails_closed(tmp_path: Path) -> None:
    """D1: un id inexistente es un ERROR, no un exit 0 silencioso.

    Si saliera 0, el operador creeria haber promovido algo que no existe: la
    trampa del "exit 0 = no hice nada" otra vez.

    NO basta con `returncode != 0`: un argparse que no conozca el flag tambien
    da != 0, asi que ese assert pasaria SIN la feature (falso verde real, cazado
    por la review adversarial y reproducido borrando el flag: el test seguia
    verde). Por eso se afirma sobre el MENSAJE de la logica de negocio.
    """
    canon, _ = _make_worktree_pair(tmp_path)
    _write(canon / OBS_REL, [_obs_id("obs-uno", "tema-uno", "WOT-2026-026f")])

    r = _run_promote(canon, "obs-INEXISTENTE")

    assert r.returncode == 1, f"rc esperado 1 (fallo de negocio), no {r.returncode}"
    out = r.stdout + r.stderr
    assert "obs-INEXISTENTE" in out, (
        f"el error debe NOMBRAR el id que no encontro; got: {out}"
    )
    assert "no se promueve lo que no existe" in out, (
        f"debe fallar por la LOGICA, no por argparse; got: {out}"
    )
    assert len(_load(canon / _archive_rel())) == 0


def test_promote_id_dry_run_writes_nothing(tmp_path: Path) -> None:
    """D1: sin --apply no se escribe (confirmacion explicita)."""
    canon, _ = _make_worktree_pair(tmp_path)
    _write(canon / OBS_REL, [_obs_id("obs-uno", "tema-uno", "WOT-2026-026f")])

    r = _run_promote(canon, "obs-uno", apply=False)

    assert r.returncode == 0
    assert _load(canon / _archive_rel()) == []


def test_promote_id_refuses_to_write_onto_an_invalid_archive(tmp_path: Path) -> None:
    """D1: `--strict` ANTES de escribir (fail-closed), como la via automatica.

    Sin esta mitad, la via curada seria un bypass de la barrera que protege la
    memoria portable: promoveria sobre un archive ya invalido.

    Como en el test de arriba, `returncode != 0` NO basta (argparse tambien lo
    da): se afirma sobre el mensaje fail-closed del reconciliador.
    """
    canon, _ = _make_worktree_pair(tmp_path)
    _write(canon / OBS_REL, [_obs_id("obs-uno", "tema-uno", "WOT-2026-026f")])
    bad = _obs("malo", "WOT-2026-000a")
    bad["applies_to"] = "process"  # fuera del enum VALID_APPLIES_TO
    _write(canon / _archive_rel(), [bad])

    r = _run_promote(canon, "obs-uno")

    assert r.returncode == 1, f"rc esperado 1 (fail-closed), no {r.returncode}"
    out = r.stdout + r.stderr
    assert "NO valida --strict" in out, (
        f"debe negarse por la VALIDACION del archive, no por argparse; got: {out}"
    )
    assert len(_load(canon / _archive_rel())) == 1, "no anadio nada"


def test_default_reconcile_on_canonical_is_still_a_noop(tmp_path: Path) -> None:
    """No-regresion: SIN --promote-id, el canonico sigue siendo no-op.

    D1 es ADITIVA. Si el comportamiento por defecto cambiara, la via automatica
    por antiguedad (B1) quedaria cortocircuitada.
    """
    canon, _ = _make_worktree_pair(tmp_path)
    _write(canon / OBS_REL, [_obs_id("obs-uno", "tema-uno", "WOT-2026-026f")])

    r = _run(canon)

    assert r.returncode == 0
    assert "YA es el checkout canonico" in r.stdout
    assert _load(canon / _archive_rel()) == []
